import {
  ab,
  type FactionData,
  type HeroData,
  type PowerData,
  type StructureData,
  type UnitData,
  up,
} from './types';

/**
 * Gondor in Age of the Ring 9.2.0 (the 2025 edition). Numbers come from
 * the community wiki (aotr.fandom.com, CC BY-SA) checked against the mod's
 * own notes; the prose is ours. 9.3.0 changes are applied as a patch in the
 * seed, not duplicated here.
 */

// Common equipment, priced per battalion at the Blacksmith.
const FORGED_BLADES = up(
  'Hojas forjadas',
  300,
  'C',
  'Más daño cuerpo a cuerpo. Hay que investigar Hojas templadas en la Herrería (nivel 2).',
  null,
  { costResearch: 1000 },
);
const HEAVY_ARMOUR = up(
  'Armadura pesada',
  300,
  'T',
  'Reduce mucho el daño recibido. Hay que investigar Corazas de acero en la Herrería (nivel 2).',
  null,
  { costResearch: 1000 },
);
const BANNER = up(
  'Portaestandarte',
  100,
  'V',
  'El batallón sube a nivel 2 y repone bajas junto al estandarte. Investigar Estandartes del Árbol Blanco en la Herrería.',
  null,
  { costResearch: 400, levelGranted: 2 },
);
const FIRE_ARROWS = up(
  'Flechas de fuego',
  300,
  'C',
  'Mucho más daño con el arco, sobre todo a edificios y asedio. Investigar en el Campo de tiro nivel 3.',
  null,
  { costResearch: 1000 },
);
const ARMAMENTS = ab(
  'Armas de la Ciudad Blanca',
  4,
  null,
  'passive',
  'Al llegar a nivel 4 el batallón gana +20 % de armadura para siempre. Se acumula con liderazgos y hechizos.',
  { armourPct: 20 },
);
const BOMBARD = ab(
  'Bombardeo',
  null,
  'W',
  'active',
  'Dispara sin parar sobre una zona hasta que se le ordena otra cosa.',
);

const units: UnitData[] = [
  {
    slug: 'builder',
    name: 'Constructor',
    category: 'special',
    recruitedAt: 'Fortaleza',
    cost: 500,
    cp: 0,
    health: 625,
    armourSet: 'PorterArmor',
    strongAgainst: [],
    weakAgainst: ['melee', 'ranged'],
    description:
      'Levanta todos los edificios de Gondor (la Fortaleza la construye desde el palantir por falta de hueco en el menú). No ataca y cuesta 500: hay que protegerlo. Estandartes del Árbol Blanco lo abarata un 20 %.',
    abilities: [
      ab('Apagar fuego', null, null, 'active', 'Apaga incendios cercanos.'),
    ],
    images: { portrait: 'Gondor Porter Portrait.PNG' },
  },
  {
    slug: 'lamedon-clansmen',
    name: 'Clanes de Lamedon',
    category: 'swordsmen',
    recruitedAt: 'Cuartel nivel 1',
    cost: 250,
    cp: 60,
    health: 190,
    armourSet: 'SoldierArmor',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['pikemen'],
    weakAgainst: ['cavalry', 'monsters'],
    description:
      'La espada barata de los feudos: montañeses de Lamedon curtidos contra los sureños. Sirven para la defensa temprana, el acoso y para limpiar guaridas; en cuanto llega el Cuartel de nivel 2 los sustituyen los Soldados de Minas Tirith. Merece la pena mantenerlos vivos hasta el nivel 4 por Armas de la Ciudad Blanca.',
    abilities: [ARMAMENTS],
    upgrades: [FORGED_BLADES, BANNER],
    images: {
      portrait: 'Lamedon Portrait.PNG',
      ingame: 'LamedonClansmen.png',
    },
  },
  {
    slug: 'linhir-spearmen',
    name: 'Lanceros de Linhir',
    category: 'pikemen',
    recruitedAt: 'Cuartel nivel 1',
    cost: 300,
    cp: 60,
    health: 215,
    armourSet: 'PikemenArmor',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['cavalry', 'monsters'],
    weakAgainst: ['swordsmen'],
    description:
      'Las picas de nivel 1. Para limpiar guaridas de wargos y troles y para parar la primera caballería. No pueden comprar armadura pesada, así que en la partida larga dependen de subir a nivel 4.',
    abilities: [
      ab(
        'Formación puercoespín',
        null,
        'W',
        'formation',
        'Círculo de picas hacia fuera. El batallón no se mueve y gana +50 % de armadura.',
        { armourPct: 50 },
      ),
      ARMAMENTS,
    ],
    upgrades: [FORGED_BLADES, BANNER],
    images: { portrait: 'Linhir Portrait.PNG', ingame: 'LinhirSpearmen.png' },
  },
  {
    slug: 'blackroot-vale-archers',
    name: 'Arqueros del Valle de la Raíz Negra',
    category: 'archers',
    recruitedAt: 'Campo de tiro nivel 1',
    cost: 250,
    cp: 60,
    health: 200,
    armourSet: 'ArcherArmor',
    attackType: 'A distancia, un objetivo',
    strongAgainst: ['ranged'],
    weakAgainst: ['cavalry', 'siege'],
    description:
      'Los quinientos arqueros de Duinhir. Baratos y numerosos, hacen el daño de Gondor en la partida temprana. Con estandarte y flechas de fuego aguantan hasta nivel 4; sin picas delante, la caballería los borra.',
    abilities: [BOMBARD, ARMAMENTS],
    upgrades: [BANNER, FIRE_ARROWS],
    images: {
      portrait: 'Blackroot Portrait.PNG',
      ingame: 'Blackroot Archers.png',
    },
  },
  {
    slug: 'pinnath-gelin-riders',
    name: 'Jinetes de Pinnath Gelin',
    category: 'cavalry',
    recruitedAt: 'Establos nivel 1',
    cost: 500,
    cp: 70,
    health: 300,
    armourSet: 'PKnightArmor',
    attackType: 'Cuerpo a cuerpo y carga',
    strongAgainst: ['swordsmen', 'archers'],
    weakAgainst: ['pikemen', 'monsters'],
    description:
      'Los trescientos de Hirluin. Caballería básica para acosar la economía enemiga y flanquear arqueros. Poca armadura: cargar y salir, no quedarse. Los Caballeros de Minas Tirith los reemplazan a mitad de partida.',
    abilities: [ARMAMENTS],
    upgrades: [BANNER, FORGED_BLADES],
    images: {
      portrait: 'Pinnath Gelin Portrait.PNG',
      ingame: 'Pinnath Gelin Riders.png',
    },
  },
  {
    slug: 'lossarnach-axemen',
    name: 'Hacheros de Lossarnach',
    category: 'swordsmen',
    recruitedAt: 'Cuartel nivel 1',
    requirements: 'Forlong reclutado',
    cost: 450,
    cp: 75,
    health: 200,
    armourSet: 'SoldierArmor',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['pikemen', 'structures'],
    weakAgainst: ['cavalry', 'monsters'],
    description:
      'Los hombres de Forlong: tropa de choque con hacha. Pegan mucho más que los Clanes y derriban edificios muy deprisa, a cambio de una armadura floja hasta el nivel 4. Ideales para incursiones contra la economía rival.',
    abilities: [ARMAMENTS],
    upgrades: [BANNER, FORGED_BLADES],
    images: {
      portrait: 'Lossanarch Portrait.PNG',
      ingame: 'Lossarnach Axemen.png',
    },
  },
  {
    slug: 'minas-tirith-soldiers',
    name: 'Soldados de Minas Tirith',
    category: 'swordsmen',
    recruitedAt: 'Cuartel nivel 2',
    cost: 500,
    cp: 75,
    health: 350,
    armourSet: 'SoldierEliteArmor',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['pikemen'],
    weakAgainst: ['cavalry', 'monsters'],
    description:
      'La columna vertebral del ejército: la espada de élite accesible (la otra, Dol Amroth, está detrás de un poder de 15 PP). Mejorables del todo, con formación y carga. El plan de Gondor es sustituir a los Clanes por ellos hacia la mitad de la partida.',
    abilities: [
      ab(
        'Muro de escudos',
        null,
        'W',
        'formation',
        '+40 % de armadura y resistencia a flechas a cambio de -33 % de velocidad.',
        { armourPct: 40, speedPct: -33 },
      ),
      ab(
        'Carga',
        2,
        'R',
        'active',
        'Los soldados cargan contra el objetivo con +50 % de daño y +50 % de armadura y abren camino a empujones.',
        { damagePct: 50, armourPct: 50 },
      ),
    ],
    upgrades: [BANNER, FORGED_BLADES, HEAVY_ARMOUR],
    images: {
      portrait: 'Anorien Soldier Portrait.PNG',
      ingame: 'Anorien Swordsmen.png',
    },
  },
  {
    slug: 'minas-tirith-spearmen',
    name: 'Lanceros de Minas Tirith',
    category: 'pikemen',
    recruitedAt: 'Cuartel nivel 2',
    cost: 550,
    cp: 75,
    health: 315,
    armourSet: 'TowerGuardArmor',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['cavalry', 'monsters'],
    weakAgainst: ['swordsmen'],
    description:
      'Las picas de nivel 2, con la mejor armadura de Gondor y armadura pesada comprable. Frenan caballería y monstruos para que el resto remate. El muro de lanzas los hace casi inamovibles, pero lentos y apelotonados.',
    abilities: [
      ab(
        'Muro de lanzas',
        null,
        'W',
        'formation',
        '-33 % de velocidad; +40 % de armadura, resistencia al empuje y frenan las cargas.',
        { armourPct: 40, speedPct: -33 },
      ),
    ],
    upgrades: [FORGED_BLADES, HEAVY_ARMOUR, BANNER],
    images: {
      portrait: 'Anorien Pikemen Portrait.PNG',
      ingame: 'AnorienSpears.png',
    },
  },
  {
    slug: 'minas-tirith-archers',
    name: 'Arqueros de Minas Tirith',
    category: 'archers',
    recruitedAt: 'Campo de tiro nivel 2',
    cost: 500,
    cp: 75,
    health: 255,
    armourSet: 'ArcherEliteArmor',
    attackType: 'A distancia, un objetivo',
    strongAgainst: ['ranged'],
    weakAgainst: ['siege', 'cavalry'],
    description:
      'Los arqueros acorazados de la Ciudad Blanca. Menos daño puro que los Montaraces pero mucha más armadura y flechas de fuego, que los hacen letales contra edificios y máquinas. Faramir los apoya bien.',
    abilities: [
      BOMBARD,
      ab(
        'Formación de escaramuza',
        2,
        'R',
        'formation',
        '+25 % de daño y +15 % de velocidad a costa de -50 % de armadura.',
        { damagePct: 25, speedPct: 15, armourPct: -50 },
      ),
    ],
    upgrades: [HEAVY_ARMOUR, FIRE_ARROWS, BANNER],
    images: {
      portrait: 'Anorien Archer Portrait.PNG',
      ingame: 'AnorienArchers.png',
    },
  },
  {
    slug: 'ithilien-rangers',
    name: 'Montaraces de Ithilien',
    category: 'archers',
    recruitedAt: 'Campo de tiro nivel 3',
    requirements: 'Faramir reclutado',
    cost: 625,
    cp: 72,
    health: 250,
    armourSet: 'IthilienRangerArmor',
    attackType: 'A distancia o espada',
    strongAgainst: ['ranged', 'infantry'],
    weakAgainst: ['cavalry'],
    description:
      'Los hombres de Faramir: arqueros de élite que se ocultan entre los árboles, cambian a espada cuando el enemigo se acerca y bombardean a gran distancia. La unidad más versátil de Gondor.',
    abilities: [
      BOMBARD,
      ab(
        'Cambiar de arma',
        null,
        'R',
        'toggle',
        'Alterna arcos y espadas. Con espadas ganan +50 % de armadura.',
        { armourPctMelee: 50 },
      ),
      ab(
        'Disparo largo',
        3,
        'T',
        'active',
        'Una descarga de flechas sobre cualquier punto dentro de un radio enorme.',
      ),
    ],
    upgrades: [
      BANNER,
      up(
        'Flechas de punzón',
        300,
        'C',
        'Cada impacto reduce un 25 % la armadura del objetivo contra flechas. Se investiga en el Campo de tiro (nivel 3, tras Flechas de fuego).',
        null,
        { armourReductionPct: 25 },
      ),
    ],
    images: {
      portrait: 'Ithilien Ranger Portrait.PNG',
      ingame: 'Ithilien Rangers Bows.png',
    },
  },
  {
    slug: 'minas-tirith-knights',
    name: 'Caballeros de Minas Tirith',
    category: 'cavalry',
    recruitedAt: 'Establos nivel 2',
    cost: 650,
    cp: 80,
    health: 400,
    armourSet: 'AnorienKnightArmor',
    attackType: 'Cuerpo a cuerpo y carga',
    strongAgainst: ['swordsmen', 'archers'],
    weakAgainst: ['pikemen', 'monsters'],
    description:
      'La caballería de élite accesible (los Caballeros del Cisne exigen 15 PP). Para acosar la economía o flanquear espadas y arqueros. Faramir montado les da +25 % de daño.',
    abilities: [
      ab(
        'Formación en cuña',
        null,
        'W',
        'formation',
        '-25 % de armadura; la carga frena mucho menos al atravesar enemigos.',
        { armourPct: -25, crushDeceleration: -50 },
      ),
    ],
    upgrades: [BANNER, FORGED_BLADES, HEAVY_ARMOUR],
    images: {
      portrait: 'Anorien Knight Portrait.PNG',
      ingame: 'Anorien Knights.png',
    },
  },
  {
    slug: 'trebuchet',
    name: 'Trabuquete',
    category: 'siege',
    recruitedAt: 'Taller de asedio nivel 1',
    cost: 600,
    cp: 30,
    health: 2000,
    armourSet: 'TrebuchetArmor',
    attackType: 'Asedio a distancia',
    strongAgainst: ['structures', 'archers'],
    weakAgainst: ['melee'],
    description:
      'El asedio de Gondor. Alcanza más lejos que las torres de una fortaleza y su impacto empuja tropas. Indefenso cuerpo a cuerpo: siempre con escolta contra la caballería.',
    abilities: [
      ab(
        'Disparo automático',
        null,
        'W',
        'toggle',
        'Dispara solo a lo que se acerque, o solo cuando se le ordena.',
      ),
      ab('Bombardeo', null, 'R', 'active', 'Artillería sobre una zona.'),
    ],
    upgrades: [
      up(
        'Piedras de fuego',
        300,
        'T',
        'Proyectiles incendiarios: mucho más daño. Se investiga en el Taller de asedio nivel 2.',
      ),
    ],
    images: {
      portrait: 'Gondor Trebuchet Portrait.PNG',
      ingame: 'Trebuchet.png',
    },
  },
  {
    slug: 'dol-amroth-men-at-arms',
    name: 'Hombres de armas de Dol Amroth',
    category: 'swordsmen',
    recruitedAt: 'Ciudadela de Dol Amroth',
    requirements: 'Poder Ciudadela de Dol Amroth (15 PP)',
    cost: 700,
    cp: 80,
    health: 525,
    armourSet: 'BlackNumenoreanArmor',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['pikemen'],
    weakAgainst: ['archers', 'cavalry'],
    description:
      'Infantería pesada de Belfalas, mejores en todo que los Soldados de Minas Tirith. Se curan fuera de combate y con Salir al ataque arrastran a los feudos a la partida tardía.',
    abilities: [
      ab(
        'Sangre de los Eldar',
        null,
        null,
        'passive',
        'Las tropas de Dol Amroth se curan despacio fuera de combate.',
      ),
      ab(
        'Salir al ataque',
        2,
        'R',
        'active',
        'Ellos y los feudos cercanos ganan +33 % de daño y resistencia al empuje durante 15 s.',
        { damagePct: 33, durationS: 15 },
      ),
      ARMAMENTS,
    ],
    upgrades: [BANNER, FORGED_BLADES],
    images: {
      portrait: 'Dol Amroth Portrait.PNG',
      ingame: 'DAMenAtArms.png',
    },
  },
  {
    slug: 'swan-knights',
    name: 'Caballeros del Cisne',
    category: 'cavalry',
    recruitedAt: 'Ciudadela de Dol Amroth',
    requirements: 'Poder Ciudadela de Dol Amroth (15 PP)',
    cost: 1300,
    cp: 100,
    health: 700,
    maxCount: 3,
    armourSet: 'DolAmrothKnightArmor',
    attackType: 'Cuerpo a cuerpo y carga',
    strongAgainst: ['swordsmen', 'archers'],
    weakAgainst: ['pikemen'],
    description:
      'La mejor caballería de Gondor y de las mejores del juego. No necesitan mejoras y llegan con estadísticas altas; máximo tres batallones. Las picas siguen siendo su muerte.',
    abilities: [
      ab(
        'Sangre de los Eldar',
        null,
        null,
        'passive',
        'Se curan despacio fuera de combate.',
      ),
      ab(
        '¡Amroth por Gondor!',
        5,
        'R',
        'active',
        '+33 % de daño, +33 % de armadura y una carga que nada frena.',
        { damagePct: 33, armourPct: 33, crushDeceleration: -50 },
      ),
    ],
    upgrades: [BANNER],
    images: {
      portrait: 'Swan Knight Portrait.PNG',
      ingame: 'SwanKnights-0.png',
    },
  },
  {
    slug: 'fountain-guards',
    name: 'Guardias de la Fuente',
    category: 'heroic',
    recruitedAt: 'Fortaleza',
    requirements: 'Mejora Torre de Ecthelion',
    cost: 1500,
    cp: 120,
    health: 750,
    maxCount: 2,
    armourSet: 'FountainGuardArmor',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['cavalry', 'monsters'],
    weakAgainst: ['ranged'],
    description:
      'Los guardianes silenciosos del Árbol Blanco, con armas de mithril. La única unidad heroica de Gondor y la más dura del ejército: un muro de lanzas que ninguna caballería rompe, con auras que refuerzan la base entera.',
    abilities: [
      ab(
        'Muro de lanzas',
        null,
        'W',
        'formation',
        '+40 % de armadura e inmunidad a empuje, miedo, terror y penalizaciones; -33 % de velocidad.',
        { armourPct: 40, speedPct: -33 },
      ),
      ab(
        'Esperanza imperecedera',
        null,
        null,
        'passive',
        '+10 % de armadura por cada batallón de Minas Tirith cercano, hasta +50 %. Cuando muere un guardia, cura un poco a los aliados de alrededor.',
        { armourPctPerBattalion: 10, armourPctMax: 50 },
      ),
      ab(
        'Recuperación valerosa',
        2,
        null,
        'passive',
        'Recuperan vida fuera de combate.',
      ),
      ab(
        'Expulsar',
        3,
        'T',
        'active',
        '+33 % de daño y empujan a los enemigos durante 30 s.',
        { damagePct: 33, durationS: 30 },
      ),
      ab(
        'Defensores fervientes',
        7,
        'C',
        'active',
        'Aura de 30 s: enemigos con -25 % de daño y armadura; estructuras aliadas con +100 % de armadura; héroes aliados recargan un 50 % más rápido; los batallones cercanos reponen bajas.',
        { durationS: 30, enemyDamagePct: -25, structureArmourPct: 100 },
      ),
    ],
    images: {
      portrait: 'Fountain Guard Portrait.PNG',
      ingame: 'FountainGuard.png',
    },
  },
  {
    slug: 'rohirrim-warriors',
    name: 'Guerreros Rohirrim',
    category: 'cavalry',
    recruitedAt: 'Poder El Juramento de Eorl (15 PP)',
    isSummon: true,
    health: 600,
    armourSet: 'RohirrimArmor',
    attackType: 'Cuerpo a cuerpo y carga',
    strongAgainst: ['swordsmen', 'archers'],
    weakAgainst: ['pikemen', 'monsters'],
    description:
      'Tres batallones de la mejor caballería de la Tierra Media durante 90 s. Cargan, arrasan y se van: hay que planear el ataque antes de invocarlos.',
    abilities: [
      ab(
        'Formación en cuña',
        null,
        'W',
        'formation',
        '-25 % de armadura; la carga apenas frena.',
        { armourPct: -25, crushDeceleration: -50 },
      ),
    ],
    stats: { durationS: 90, battalions: 3 },
    images: { portrait: 'Rohirrim Portrait.PNG', ingame: 'Rohirrim.png' },
  },
  {
    slug: 'giant-eagle',
    name: 'Águila gigante',
    category: 'monster',
    recruitedAt: 'Poder Los Mensajeros de Manwë (25 PP)',
    isSummon: true,
    health: 3000,
    armourSet: 'EagleArmor',
    attackType: 'Cuerpo a cuerpo en área con empuje',
    strongAgainst: ['infantry', 'cavalry'],
    weakAgainst: ['archers'],
    description:
      'Tres águilas acompañan a Gwaihir durante 80 s. Voladoras: solo los arqueros les hacen daño, y ellas rompen cualquier formación.',
    stats: { durationS: 80, count: 3 },
    images: { portrait: 'Eagle Portrait.PNG', ingame: 'Giant Eagle.png' },
  },
  {
    slug: 'gondor-royal-guard',
    name: 'Guardia Real de Gondor',
    category: 'swordsmen',
    recruitedAt: 'Poder El Retorno del Rey (25 PP)',
    isSummon: true,
    health: 2400,
    armourSet: 'HeroArmor',
    attackType: 'Cuerpo a cuerpo, un objetivo',
    strongAgainst: ['infantry'],
    weakAgainst: ['cavalry', 'heroes'],
    description:
      'Cuatro guardias con más vida que muchos héroes escoltan a Elessar durante 120 s. Sin habilidades: pura fuerza para despejar lo que rodee al Rey.',
    stats: { durationS: 120, count: 4 },
    images: {
      portrait: 'Citadel Guard Portrait.PNG',
      ingame: 'GondorRoyalGuard.png',
    },
  },
];

const heroes: HeroData[] = [
  {
    slug: 'pippin',
    name: 'Pippin',
    title: 'Peregrin Tuk, guardia de la Ciudadela',
    recruitedAt: 'Fortaleza',
    cost: 325,
    buildTime: 20,
    health: 550,
    armourSet: 'HeroArmor',
    attackType: 'Un objetivo, espada o piedras',
    description:
      'El más joven de la Compañía, que juró fidelidad a Denethor y salvó a Faramir de la pira. El héroe más barato de Gondor: sale al principio para limpiar guaridas y, sobre todo, para que el resto de héroes suban de nivel más rápido.',
    abilities: [
      ab(
        'Piedras o espada',
        1,
        'W',
        'toggle',
        'Alterna entre tirar piedras y luchar cuerpo a cuerpo.',
      ),
      ab(
        'Capa élfica',
        1,
        'R',
        'active',
        'Se vuelve invisible mientras está quieto.',
      ),
      ab(
        'Hoja del Oesternesse',
        3,
        null,
        'passive',
        '+200 % de daño contra los Nazgûl.',
        { damagePctVsNazgul: 200 },
      ),
      ab(
        'Coraje de mediano',
        5,
        null,
        'passive',
        'Los héroes cercanos ganan experiencia un 15 % más rápido. Pippin gana vida.',
        { heroXpPct: 15 },
      ),
      ab(
        'Azote de troles',
        10,
        'V',
        'active',
        '+150 % de armadura, resistencia al empuje y +250 % de daño contra monstruos durante 20 s.',
        { armourPct: 150, damagePctVsMonsters: 250, durationS: 20 },
      ),
    ],
    images: { portrait: 'Pippin.PNG', ingame: 'Pippin ingame.png' },
  },
  {
    slug: 'forlong',
    name: 'Forlong',
    title: 'Señor de Lossarnach',
    recruitedAt: 'Fortaleza',
    cost: 1200,
    buildTime: 35,
    health: 2600,
    armourSet: 'HeroArmor',
    attackType: 'Cuerpo a cuerpo en área',
    description:
      'Gordo, viejo y valiente: trajo trescientos hacheros a la Ciudad Blanca. Reclutarlo desbloquea a los Hacheros de Lossarnach y su liderazgo lleva a los feudos al nivel 4 antes, que es cuando empiezan a aguantar.',
    abilities: [
      ab(
        'Señor de Lossarnach',
        null,
        null,
        'leadership',
        'Las tropas de los feudos cercanas ganan experiencia un 33 % más rápido y son inmunes al miedo.',
        { xpPct: 33 },
      ),
      ab(
        'Vitalidad',
        3,
        'R',
        'active',
        'Durante un rato empuja con cada golpe y gana +50 % de daño y +25 % de velocidad.',
        { damagePct: 50, speedPct: 25 },
      ),
      ab(
        'Corazón fiel, amigo fiel',
        7,
        'T',
        'active',
        'Un héroe aliado gana +50 % de armadura, +50 % de experiencia y recarga sus poderes un 75 % más rápido. No funciona con Elessar.',
        { armourPct: 50, xpPct: 50, rechargePct: 75 },
      ),
    ],
    images: { portrait: 'Forlong.png', ingame: 'Forlong ingame.png' },
  },
  {
    slug: 'beregond',
    name: 'Beregond',
    title: 'Guardia de la Ciudadela',
    recruitedAt: 'Fortaleza',
    cost: 1400,
    buildTime: 40,
    health: 2000,
    armourSet: 'HeroArmor',
    attackType: 'Un objetivo, arco o lanza',
    description:
      'El guardia de la Tercera Compañía que desobedeció al Senescal para salvar a Faramir. Alterna arco y lanza, blinda los edificios de alrededor y hace más fuertes a Faramir, Boromir y Pippin cuando están cerca. El héroe de un Gondor que se atrinchera.',
    abilities: [
      ab('Cambiar de arma', null, 'W', 'toggle', 'Alterna arco y lanza.'),
      ab(
        'Defensor de la Ciudad Blanca',
        2,
        'R',
        'active',
        'Con arco, un flechazo devastador que derriba; con lanza, un golpe pesado que empuja. Usar una forma pone en enfriamiento la otra.',
      ),
      ab(
        'Guardia de la Ciudadela',
        5,
        null,
        'passive',
        'Las estructuras cercanas ganan +30 % de armadura.',
        { structureArmourPct: 30 },
      ),
      ab(
        'Lealtad feroz',
        7,
        null,
        'passive',
        'Faramir, Boromir y Pippin ganan +15 % de armadura y +15 % de daño cerca de Beregond.',
        { armourPct: 15, damagePct: 15 },
      ),
      ab(
        'Sacrificio',
        8,
        'V',
        'active',
        'Beregond recibe un daño enorme y el héroe aliado elegido se vuelve inmune un rato.',
      ),
    ],
    images: { portrait: 'Beregond.png', ingame: 'Beregond ingame.png' },
  },
  {
    slug: 'denethor',
    name: 'Denethor',
    title: 'Senescal de Gondor',
    recruitedAt: 'Fortaleza',
    cost: 1800,
    buildTime: 50,
    health: 2200,
    armourSet: 'HeroArmor',
    attackType: 'Cuerpo a cuerpo, un objetivo',
    description:
      'El vigésimo sexto Senescal, roto por el palantir. Pelea mal, pero su liderazgo crece con el nivel y su guardia lo protege. El precio: debilita a Faramir, a Gandalf y a Elessar cuando están a su lado, así que obliga a repartir el ejército.',
    abilities: [
      ab(
        'Senescal de Gondor',
        1,
        null,
        'leadership',
        'Sus guardias lo protegen. Aliados cercanos: +25 % de armadura (nivel 1), +25 % de daño (nivel 3) y +25 % de experiencia (nivel 6). Faramir, Gandalf y Elessar pierden un 15 % de armadura junto a él.',
        { armourPct: 25, damagePctAt3: 25, xpPctAt6: 25, allyPenaltyPct: -15 },
      ),
      ab(
        'Piedra de Anárion',
        1,
        'R',
        'active',
        'Revela el mapa en una zona y quita todo liderazgo a las tropas que toca, amigas o enemigas.',
      ),
      ab(
        'Alta autoridad',
        3,
        'T',
        'active',
        'Las tropas elegidas huyen despavoridas.',
      ),
      ab(
        'Al servicio del Senescal',
        6,
        'C',
        'active',
        'Invoca un batallón temporal de Guardias de la Ciudadela; a nivel 10 también a Berethor.',
      ),
      ab(
        'Duelo de voluntades',
        9,
        'V',
        'active',
        'Sobre un héroe aliado: +100 % de daño y -50 % de armadura 15 s. Sobre un enemigo: -33 % de armadura y velocidad 15 s.',
        { damagePct: 100, armourPct: -50, durationS: 15 },
      ),
    ],
    images: { portrait: 'Denethor.PNG', ingame: 'DenethorInGame.png' },
  },
  {
    slug: 'boromir',
    name: 'Boromir',
    title: 'Capitán de la Torre Blanca',
    recruitedAt: 'Fortaleza',
    cost: 2000,
    buildTime: 60,
    health: 2400,
    armourSet: 'ToughHeroArmor',
    attackType: 'Cuerpo a cuerpo en área con empuje',
    description:
      'El primogénito de Denethor, un luchador puro. Es la primera línea de Gondor desde la mitad de la partida: su liderazgo hace fuertes a las tropas de Minas Tirith y el Cuerno de Gondor paraliza a todo lo que le rodea, la preparación perfecta para un Estallido de Gandalf o una descarga de Faramir.',
    abilities: [
      ab(
        'Capitán de la Torre Blanca',
        null,
        null,
        'leadership',
        'Soldados, Lanceros y Arqueros de Minas Tirith cercanos ganan +33 % de daño y +25 % de armadura. A nivel 5 se pone la armadura de Gondor y gana +15 % de armadura.',
        { damagePct: 33, armourPct: 25, selfArmourPctAt5: 15 },
      ),
      ab(
        'Lanzar cuchillo',
        2,
        'W',
        'active',
        'Derriba a una unidad y le quita un 25 % de armadura durante 10 s.',
        { armourReductionPct: 25, durationS: 10 },
      ),
      ab(
        'Cuerno de Gondor',
        4,
        'R',
        'active',
        'Los enemigos de alrededor quedan paralizados de miedo 15 s.',
        { durationS: 15 },
      ),
      ab(
        '¡Por Gondor!',
        5,
        'C',
        'active',
        'Las tropas elegidas ganan +33 % de daño, +20 % de velocidad y resistencia al miedo y al terror durante 30 s.',
        { damagePct: 33, speedPct: 20, durationS: 30 },
      ),
      ab(
        'Orgulloso, terco, fuerte',
        7,
        'V',
        'active',
        'Da mucha experiencia a un batallón.',
      ),
      ab(
        'Último aliento',
        null,
        null,
        'passive',
        'Al bajar del 25 % de vida gana +200 % de armadura 15 s (una vez por minuto).',
        { armourPct: 200, durationS: 15, cooldownS: 60 },
      ),
    ],
    images: { portrait: 'Boromir.PNG', ingame: 'Boromir ingame.png' },
  },
  {
    slug: 'faramir',
    name: 'Faramir',
    title: 'Capitán de Ithilien',
    recruitedAt: 'Fortaleza',
    cost: 2000,
    buildTime: 60,
    health: 2000,
    armourSet: 'LegolasArmor',
    attackType: 'A distancia, espada o carga a caballo',
    description:
      'El hijo menor, guerrero y erudito. Es el héroe más versátil del mod: arco, espada o caballo. A pie lidera a los Montaraces (que él mismo desbloquea); montado, a los Caballeros. Su Descarga oculta castiga a cualquier ejército apelotonado.',
    abilities: [
      ab('Cambiar de arma', null, 'W', 'toggle', 'Alterna arco y espada.'),
      ab(
        'Descarga oculta',
        null,
        'R',
        'active',
        'Sus montaraces disparan una lluvia de flechas sobre cualquier punto de un radio enorme. A nivel 5, +50 % de daño y más radio.',
        { damagePctAt5: 50 },
      ),
      ab(
        'Caballero o montaraz',
        null,
        'T',
        'toggle',
        'Monta o desmonta. Cambia su liderazgo y sus habilidades.',
      ),
      ab(
        'Capitán de Ithilien',
        3,
        'C',
        'active',
        'A pie: planta un grupo de montaraces ocultos e inmóviles que emboscan a quien pase (más grande a nivel 7). Además, liderazgo: los Montaraces de Ithilien cercanos ganan +15 % de armadura y daño y +50 % de experiencia.',
        { rangersArmourPct: 15, rangersDamagePct: 15, rangersXpPct: 50 },
      ),
      ab(
        'Flecha hiriente',
        6,
        'V',
        'active',
        'Con arco: un disparo que hace huir a un monstruo.',
      ),
      ab(
        'Pupilo del mago',
        3,
        null,
        'leadership',
        'Montado: los Caballeros de Minas Tirith ganan +25 % de daño y sus cargas frenan un 25 % menos.',
        { knightsDamagePct: 25, crushDeceleration: -25 },
      ),
      ab(
        'Carga desesperada',
        3,
        'R',
        'active',
        'Montado: +100 % de resistencia a flechas y picas durante 20 s.',
        { pierceResistPct: 100, durationS: 20 },
      ),
      ab(
        'La calidad de Faramir',
        8,
        'C',
        'active',
        'Montado: da experiencia a las tropas elegidas.',
      ),
    ],
    images: { portrait: 'Faramir.PNG', ingame: 'Faramir Bow.png' },
  },
  {
    slug: 'imrahil',
    name: 'Imrahil',
    title: 'Príncipe de Dol Amroth',
    recruitedAt: 'Ciudadela de Dol Amroth',
    cost: 1700,
    buildTime: 40,
    health: 2800,
    armourSet: 'ToughHeroArmor',
    attackType: 'Cuerpo a cuerpo, a pie o montado',
    description:
      'El cuñado de Denethor, que cabalgó con setecientos caballeros a la Ciudad Blanca. Solo aparece tras levantar la Ciudadela de Dol Amroth con el libro de poderes. Su liderazgo sirve tanto a las tropas del Cisne como a los feudos, y montado convierte la caballería en un ariete.',
    abilities: [
      ab('Montar o desmontar', null, 'W', 'toggle', 'Sube o baja del caballo.'),
      ab(
        'Señor justo',
        null,
        null,
        'leadership',
        'Las tropas de los feudos y de Dol Amroth cercanas ganan +33 % de daño y +33 % de armadura.',
        { damagePct: 33, armourPct: 33 },
      ),
      ab(
        'Indemne',
        3,
        'T',
        'active',
        'Inmune a flechas, +100 % de daño, más velocidad y resistencia al empuje durante un rato.',
        { damagePct: 100 },
      ),
      ab(
        'Inspiración',
        5,
        'C',
        'active',
        'Las tropas cercanas ganan el doble de experiencia durante un minuto.',
        { xpPct: 100, durationS: 60 },
      ),
      ab(
        '¡Amroth por Gondor!',
        7,
        'V',
        'active',
        'Montado: él y la caballería cercana ganan +50 % de armadura y cargan sin frenar.',
        { armourPct: 50, crushDeceleration: -50 },
      ),
    ],
    images: { portrait: 'Imrahil.png', ingame: 'Imrahil Mounted.png' },
  },
  {
    slug: 'gandalf-the-white',
    name: 'Gandalf el Blanco',
    title: 'Jefe de los Istari',
    recruitedAt: 'Fortaleza',
    cost: 5000,
    buildTime: 80,
    health: 2900,
    armourSet: 'HeroArmor',
    attackType: 'Cuerpo a cuerpo en área',
    description:
      'Devuelto con más poder tras el Balrog, dirigió la defensa de Minas Tirith. Es el héroe caro y decisivo de Gondor: a pie destroza grupos apelotonados, montado en Sombragrís paraliza héroes, y su Llama de Anor es el mejor golpe contra Balrogs y Nazgûl.',
    abilities: [
      ab(
        'Jefe de los Istari',
        1,
        'W',
        'active',
        'A pie: un estallido cercano que empuja a los enemigos. Montado: paraliza y daña a un héroe. Además, pasiva: aliados cercanos con +300 % de armadura contra magia y elementos, +50 % de experiencia e inmunes al miedo.',
        { magicArmourPct: 300, xpPct: 50 },
      ),
      ab(
        'Burbuja de escudo',
        1,
        'U',
        'passive',
        'Cada 75 s gana +75 % de armadura y resistencia al empuje durante 10 s. Se puede disparar a mano.',
        { armourPct: 75, durationS: 10, cooldownS: 75 },
      ),
      ab('Montar a Sombragrís', 1, 'R', 'toggle', 'Sube o baja del caballo.'),
      ab(
        'Corazones reavivados',
        2,
        'T',
        'active',
        '+25 % de daño y armadura para Gandalf 30 s; los aliados cercanos son inmunes a penalizaciones y empujes mientras dura; los edificios de Gondor cercanos reclutan un 50 % más rápido 60 s.',
        { damagePct: 25, armourPct: 25, durationS: 30, recruitSpeedPct: 50 },
      ),
      ab(
        'Llama de Anor',
        5,
        'C',
        'active',
        'Un haz de luz que daña, con bonus contra Balrogs y Nazgûl. Más daño a nivel 7; a nivel 9 más radio y empuje.',
      ),
      ab(
        '¡No puedes pasar!',
        10,
        'V',
        'active',
        'Empuja y paraliza a todos los enemigos en un radio enorme.',
      ),
    ],
    images: {
      portrait: 'Gandalf the White Portrait.png',
      ingame: 'GandalfWhiteFoot.png',
    },
  },
  {
    slug: 'frodo',
    name: 'Frodo',
    title: 'Portador del Anillo',
    recruitedAt: 'Fortaleza (con el Anillo Único)',
    cost: 2000,
    buildTime: 70,
    health: 1800,
    armourSet: 'FrodoRingHeroArmor',
    attackType: 'Un objetivo, Dardo o piedras',
    description:
      'El héroe del Anillo de las facciones buenas. Parece débil al lado de Sauron o Smaug, pero su Destino de la Tierra Media es uno de los mejores liderazgos del juego y, al ser de tipo hechizo, nada lo anula. Se mantiene vivo con la invisibilidad y la Luz de Eärendil.',
    abilities: [
      ab('Piedras o Dardo', 1, 'W', 'toggle', 'Alterna piedras y espada.'),
      ab(
        'Una pesada carga',
        1,
        'R',
        'active',
        'Se vuelve invisible. Cuidado con el Ojo.',
      ),
      ab('Luz de Eärendil', 1, 'T', 'active', 'Los enemigos cercanos huyen.'),
      ab(
        'El destino de la Tierra Media',
        1,
        null,
        'passive',
        'Aliados cercanos: +50 % de daño, +50 % de armadura, experiencia al doble y recargas un 25 % más rápidas. De tipo hechizo: no se anula.',
        { damagePct: 50, armourPct: 50, xpPct: 100, rechargePct: 25 },
      ),
      ab(
        'El guía y el jardinero',
        1,
        'V',
        'active',
        'Invoca a Sam y a Sméagol a su lado.',
      ),
    ],
    images: { portrait: 'Frodo.PNG', ingame: 'Frodo_Bag_End.png' },
  },
  {
    slug: 'aragorn-elessar',
    name: 'Aragorn (Elessar)',
    title: 'Rey de Gondor y Arnor',
    recruitedAt: 'Poder El Retorno del Rey (25 PP)',
    isSummon: true,
    health: 4352,
    armourSet: 'ToughHeroArmor',
    attackType: 'Cuerpo a cuerpo en área',
    description:
      'No se recluta: llega para siempre con el poder de 25 PP, escoltado por cuatro guardias reales temporales. Cura y refuerza a los héroes, Andúril castiga a los héroes enemigos y Estel es un liderazgo activo desde la 9.2.0.',
    abilities: [
      ab('Montar a Roheryn', null, 'W', 'toggle', 'Sube o baja del caballo.'),
      ab(
        'Manos del Rey',
        null,
        'R',
        'active',
        'Cura a los héroes aliados cercanos y les da +33 % de armadura durante 30 s.',
        { armourPct: 33, durationS: 30 },
      ),
      ab(
        'Andúril, Llama del Oeste',
        null,
        'T',
        'active',
        'Un golpe con mucho daño extra contra héroes.',
      ),
      ab(
        'Estel',
        null,
        'C',
        'active',
        'Liderazgo activo con enfriamiento: los aliados cercanos ganan daño, armadura y resistencia al miedo mientras dura.',
      ),
      ab(
        'Rey de los Hombres del Oeste',
        null,
        null,
        'passive',
        'Las tropas cercanas son inmunes al miedo y al terror.',
      ),
    ],
    stats: { guards: 4, guardsDurationS: 120 },
    images: { portrait: 'Elessar Portrait.png', ingame: 'Elessar ingame.png' },
  },
  {
    slug: 'gwaihir',
    name: 'Gwaihir',
    title: 'Señor de los Vientos',
    recruitedAt: 'Poder Los Mensajeros de Manwë (25 PP)',
    isSummon: true,
    health: 3000,
    armourSet: 'EagleHeroArmor',
    attackType: 'Cuerpo a cuerpo en área con empuje',
    description:
      'La mayor de las Águilas llega con tres más durante 75 s. Volador, así que solo lo tocan los arqueros; su daño en área revienta hordas y Alas de huracán mantiene a los enemigos por los suelos.',
    abilities: [
      ab(
        'Alas de huracán',
        null,
        'W',
        'active',
        'Una onda de choque bajo el águila que daña y derriba a todo lo que hay debajo.',
      ),
    ],
    stats: { durationS: 75, eagles: 3 },
    images: { portrait: 'Gwaihir.png', ingame: 'GwaihirInGame.png' },
  },
];

const structures: StructureData[] = [
  {
    slug: 'fortress',
    name: 'Fortaleza de Gondor',
    kind: 'fortress',
    cost: 5000,
    buildTime: 120,
    health: 7500,
    armourSet: 'FortressArmor',
    description:
      'La Torre de Ecthelion sobre los siete niveles. Recluta constructores, casi todos los héroes y a los Guardias de la Fuente; dispara a los enemigos cercanos, produce 25 recursos por ciclo y es el libro de poderes de la facción.',
    produces: ['Constructor', 'Guardias de la Fuente'],
    upgrades: [
      up(
        'Estandartes del Árbol Blanco',
        500,
        'W',
        'Aliados junto a la fortaleza: +33 % de daño, +33 % de armadura y experiencia al doble. Héroes un 10 % más baratos y rápidos; constructores un 20 % más baratos.',
        null,
        { damagePct: 33, armourPct: 33, heroCostPct: -10, builderCostPct: -20 },
      ),
      up(
        'Casas de Curación',
        1000,
        'E',
        'Revivir héroes cuesta y tarda un 20 % menos. Cura a los aliados cercanos.',
        null,
        { reviveCostPct: -20, reviveTimePct: -20 },
      ),
      up(
        'Baluarte del Oeste',
        1250,
        'R',
        'Desbloquea Defensa firme: dos batallones de Guardias de la Ciudadela para defender la fortaleza durante 60 s.',
      ),
      up(
        'Munición incendiaria',
        1500,
        'T',
        'Todas las torres y trabuquetes adosados hacen daño de fuego.',
      ),
      up(
        'Cantería númenóreana',
        1500,
        'S',
        'Más armadura para la fortaleza y las murallas. Requisito de la Torre de Ecthelion.',
      ),
      up(
        'Torre de Ecthelion',
        1000,
        'D',
        'Palantir de la Torre Blanca (revela todo el mapa 30 s y detecta sigilo), Guardias de la Fuente y más visión.',
      ),
      up(
        'Expansión: Muralla',
        250,
        'W',
        'Permite construir murallas desde la fortaleza.',
      ),
      up(
        'Expansión: Torre de flechas',
        400,
        'E',
        'Torre defensiva de corto alcance.',
      ),
      up('Expansión: Trabuquete', 600, 'R', 'Arma defensiva de largo alcance.'),
      up(
        'Expansión: Estatua solemne',
        500,
        'T',
        'Guardias de la Fuente que defienden la estatua.',
      ),
    ],
    abilities: [
      ab(
        'Defensa firme',
        null,
        'T',
        'active',
        'Con Baluarte del Oeste: dos batallones de Guardias de la Ciudadela durante 60 s.',
        { durationS: 60, battalions: 2 },
      ),
      ab(
        'Palantir de la Torre Blanca',
        null,
        'D',
        'active',
        'Con Torre de Ecthelion: revela el mapa entero 30 s y detecta unidades ocultas.',
        { durationS: 30 },
      ),
    ],
    stats: { resourcesPerCycle: 25 },
    images: { ingame: 'GondFort.png' },
  },
  {
    slug: 'farm',
    name: 'Granja',
    kind: 'economy',
    cost: 300,
    buildTime: 15,
    health: 2000,
    healthByLevel: [2000, 2500, 3500],
    armourSet: 'ResourceArmor',
    description:
      'El recurso barato de Gondor. Produce según el terreno libre a su alrededor y sube de nivel produciendo: a nivel 2 (1500 recursos) rinde ×1,25 y a nivel 3 (3000) ×1,875 y dispara flechas. Sufre inflación.',
    bonus:
      'Pastos: la caballería cuesta un 5 % menos por granja a partir de la segunda, hasta un 20 %.',
    stats: {
      resourcesL1: 25,
      resourcesL2: 32,
      resourcesL3: 47,
      cpL1: 50,
      cpL2: 75,
      cpL3: 100,
      cavalryDiscountMaxPct: 20,
    },
    images: { ingame: 'GondorFarm1.png' },
  },
  {
    slug: 'blacksmith',
    name: 'Herrería',
    kind: 'economy',
    cost: 400,
    buildTime: 15,
    health: 1500,
    healthByLevel: [1500, 3000, 4500],
    armourSet: 'TechnologyArmor',
    description:
      'Recurso secundario y tienda de mejoras. Rinde menos que la granja (×1,12 a nivel 2 y ×1,4 a nivel 3) pero sube también gastando en mejoras. Conviene levantarla pronto para que vaya subiendo de nivel: Hojas templadas y Corazas de acero exigen nivel 2.',
    bonus:
      'Acero: las mejoras cuestan un 5 % menos por herrería a partir de la segunda, hasta un 25 %.',
    upgrades: [
      up(
        'Estandartes del Árbol Blanco',
        400,
        'W',
        'Permite comprar portaestandartes a los batallones.',
        1,
      ),
      up(
        'Hojas templadas',
        1000,
        'E',
        'Permite comprar Hojas forjadas. Requiere Herrería nivel 2.',
        2,
      ),
      up(
        'Corazas de acero',
        1000,
        'R',
        'Permite comprar Armadura pesada. Requiere Herrería nivel 2.',
        2,
      ),
    ],
    stats: {
      resourcesL1: 25,
      resourcesL2: 28,
      resourcesL3: 35,
      cpL1: 50,
      cpL2: 75,
      cpL3: 100,
      upgradeDiscountMaxPct: 25,
    },
    images: { ingame: 'BS Lvl 1.png' },
  },
  {
    slug: 'barracks',
    name: 'Cuartel',
    kind: 'production',
    cost: 350,
    buildTime: 30,
    health: 3000,
    healthByLevel: [3000, 4500, 6000],
    armourSet: 'FactoryArmor',
    description:
      'La infantería cuerpo a cuerpo: feudos a nivel 1 y tropas de Minas Tirith a nivel 2. Un segundo cuartel en vez de subirlo es la otra apuesta: masa de feudos baratos.',
    produces: [
      'Clanes de Lamedon',
      'Lanceros de Linhir',
      'Hacheros de Lossarnach',
      'Soldados de Minas Tirith',
      'Lanceros de Minas Tirith',
    ],
    upgrades: [
      up(
        'Subir a nivel 2',
        500,
        'A',
        'Soldados y Lanceros de Minas Tirith. Recluta un 10 % más rápido.',
        2,
        { recruitSpeedPct: 10 },
      ),
      up(
        'Subir a nivel 3',
        300,
        'A',
        'Recluta un 25 % más rápido y añade una torre de flechas.',
        3,
        { recruitSpeedPct: 25 },
      ),
    ],
    images: { ingame: 'GondorBarracks1.png' },
  },
  {
    slug: 'archery-range',
    name: 'Campo de tiro',
    kind: 'production',
    cost: 300,
    buildTime: 25,
    health: 3000,
    healthByLevel: [3000, 4500, 6000],
    armourSet: 'FactoryArmor',
    description:
      'Los arqueros y, a nivel 3, las Flechas de fuego y de punzón. Subirlo es la inversión que más cambia a Gondor: los arqueros son su daño.',
    produces: [
      'Arqueros del Valle de la Raíz Negra',
      'Arqueros de Minas Tirith',
      'Montaraces de Ithilien',
    ],
    upgrades: [
      up(
        'Subir a nivel 2',
        500,
        'A',
        'Arqueros de Minas Tirith. Recluta un 10 % más rápido.',
        2,
        { recruitSpeedPct: 10 },
      ),
      up(
        'Subir a nivel 3',
        500,
        'A',
        'Montaraces de Ithilien y la investigación de Flechas de fuego. Recluta un 25 % más rápido y añade una torre.',
        3,
        { recruitSpeedPct: 25 },
      ),
      up(
        'Flechas de fuego',
        1000,
        'T',
        'Permite comprar Flechas de fuego a los batallones y Flechas de punzón a los Montaraces. Requiere nivel 3.',
        3,
      ),
    ],
    images: { ingame: 'Archery Range Lvl 1.png' },
  },
  {
    slug: 'stables',
    name: 'Establos',
    kind: 'production',
    cost: 500,
    buildTime: 30,
    health: 3000,
    healthByLevel: [3000, 4500, 6000],
    armourSet: 'FactoryArmor',
    description:
      'La caballería. Más caro que los otros edificios de reclutamiento, como sus unidades: no conviene levantarlo antes de tener la economía.',
    produces: ['Jinetes de Pinnath Gelin', 'Caballeros de Minas Tirith'],
    upgrades: [
      up(
        'Subir a nivel 2',
        500,
        'A',
        'Caballeros de Minas Tirith. Recluta un 10 % más rápido.',
        2,
        { recruitSpeedPct: 10 },
      ),
      up(
        'Subir a nivel 3',
        350,
        'A',
        'Recluta un 25 % más rápido y añade una torre.',
        3,
        { recruitSpeedPct: 25 },
      ),
    ],
    images: { ingame: 'Stables Lvl 1.png' },
  },
  {
    slug: 'siege-works',
    name: 'Taller de asedio',
    kind: 'production',
    cost: 600,
    buildTime: 25,
    health: 3000,
    healthByLevel: [3000, 4500, 6000],
    armourSet: 'FactoryArmor',
    description:
      'Trabuquetes. A nivel 2 repara las máquinas cercanas y vende las Piedras de fuego. Un taller adelantado ahorra el paseo cuando el rival ya está encerrado.',
    produces: ['Trabuquete'],
    upgrades: [
      up(
        'Subir a nivel 2',
        500,
        'A',
        'Investigación de Piedras de fuego y reparación de máquinas cercanas. Recluta un 10 % más rápido.',
        2,
      ),
      up(
        'Subir a nivel 3',
        300,
        'A',
        'Repara más rápido, recluta un 25 % más rápido y añade una torre.',
        3,
      ),
      up(
        'Piedras de fuego',
        null,
        'E',
        'Permite comprar Piedras de fuego a los trabuquetes. Requiere nivel 2.',
        2,
      ),
    ],
    images: { ingame: 'Gondor Siege Lvl 1.png' },
  },
  {
    slug: 'battle-tower',
    name: 'Torre de batalla',
    kind: 'defence',
    cost: 400,
    buildTime: 45,
    health: 1500,
    armourSet: 'FortressExpansionArmor',
    description:
      'Torre que dispara a lo que se acerque; se puede guarnecer con arqueros, que disparan protegidos. Obliga al rival a traer asedio para tocar una base adelantada.',
    upgrades: [
      up(
        'Centinela de Anórien',
        150,
        'W',
        'Un centinela permanente dentro de la torre.',
      ),
    ],
    images: { ingame: 'Gondor Tower.png' },
  },
  {
    slug: 'monument-to-elendil',
    name: 'Monumento a Elendil',
    kind: 'support',
    cost: 500,
    buildTime: 45,
    health: 1875,
    armourSet: 'StructureArmor',
    description:
      'Pozo y estatua heroica en uno: los aliados cercanos ganan +25 % de daño, +25 % de armadura, +33 % de experiencia e inmunidad al miedo, y los batallones reponen vida y bajas.',
    abilities: [
      ab(
        'Memoria de Elendil',
        null,
        null,
        'leadership',
        '+25 % de daño, +25 % de armadura, +33 % de experiencia e inmunidad al miedo alrededor. Repone bajas.',
        { damagePct: 25, armourPct: 25, xpPct: 33 },
      ),
    ],
    images: { ingame: 'MonumentToElendil.png' },
  },
  {
    slug: 'marketplace',
    name: 'Mercado',
    kind: 'support',
    cost: 800,
    buildTime: 35,
    health: 3000,
    maxCount: 1,
    armourSet: 'ResourceArmor',
    description:
      'No produce, pero vende dos mejoras de economía que benefician también a los aliados de Gondor. Solo uno; mejor con varias granjas ya en pie.',
    upgrades: [
      up(
        'Gran cosecha',
        600,
        'W',
        '+12 % de recursos en las granjas mientras el Mercado siga en pie.',
        null,
        { farmIncomePct: 12 },
      ),
      up(
        'Materiales de asedio',
        650,
        'E',
        'Los edificios destruidos devuelven el 50 % de su coste.',
        null,
        { refundPct: 50 },
      ),
    ],
    images: { ingame: 'Marketplace.png' },
  },
  {
    slug: 'stoneworker',
    name: 'Cantero',
    kind: 'economy',
    cost: 650,
    buildTime: 35,
    health: 2500,
    maxCount: 5,
    armourSet: 'FactoryArmor',
    description:
      'Recurso terciario sin inflación: 10 recursos por ciclo pase lo que pase, +10 puntos de mando y +30 % de armadura para los edificios de alrededor. Cerca de la fortaleza y los cuarteles.',
    bonus:
      'Descuento en estructuras: 5 % por cantero, hasta un 25 % con cinco.',
    abilities: [
      ab(
        'Inspección de obras',
        null,
        null,
        'leadership',
        'Las estructuras cercanas ganan +30 % de armadura.',
        { structureArmourPct: 30 },
      ),
    ],
    stats: { resourcesPerCycle: 10, cp: 10, structureDiscountMaxPct: 25 },
    images: { ingame: 'Stoneworker.png' },
  },
  {
    slug: 'wall-hub',
    name: 'Muralla',
    kind: 'defence',
    cost: 300,
    buildTime: 50,
    health: 3000,
    armourSet: 'MenWallArmor',
    description:
      'Un nudo de muralla desde el que se tienden tramos (100 cada uno, 25 s). Controla el movimiento enemigo y obliga a traer asedio. La poterna deja pasar a los tuyos sin que el rival la vea; el asedio propio necesita puerta.',
    upgrades: [
      up('Nudo de muralla', 300, 'W', 'Más tramos de muralla.'),
      up('Puerta', 300, 'E', 'Puerta que se abre y cierra.'),
      up(
        'Poterna',
        500,
        'R',
        'Paso para tropas aliadas, invisible al enemigo.',
      ),
      up('Torre de flechas', 400, 'T', 'Dispara a las tropas enemigas.'),
      up('Trabuquete', 600, 'S', 'Arma defensiva de largo alcance.'),
    ],
    stats: { wallSegmentCost: 100, wallSegmentBuildTimeS: 25 },
    images: { ingame: 'Gondor Wall.png' },
  },
  {
    slug: 'dol-amroth-citadel',
    name: 'Ciudadela de Dol Amroth',
    kind: 'summoned',
    health: 5000,
    maxCount: 2,
    armourSet: 'FortressArmor',
    description:
      'Se invoca con el poder de 15 PP (máximo dos). Recluta a Imrahil, a los Hombres de armas y a los Caballeros del Cisne, dispara y produce 25 recursos por ciclo sin inflación.',
    produces: [
      'Imrahil',
      'Hombres de armas de Dol Amroth',
      'Caballeros del Cisne',
    ],
    upgrades: [
      up(
        'Estandartes de Dol Amroth',
        500,
        'R',
        'Aliados junto a la ciudadela: +33 % de daño, +33 % de armadura y +50 % de experiencia.',
        null,
        { damagePct: 33, armourPct: 33, xpPct: 50 },
      ),
      up('Foso', 1200, 'T', 'Más armadura y +1000 de vida.', null, {
        healthBonus: 1000,
      }),
    ],
    stats: { resourcesPerCycle: 25 },
    images: { ingame: 'DA Citadel.png' },
  },
];

const powers: PowerData[] = [
  {
    slug: 'captains-horn',
    name: 'Cuerno del capitán',
    tier: 1,
    position: 'L',
    kind: 'buff',
    description:
      'Las tropas elegidas ganan +25 % de daño y +25 % de armadura. Se acumula con liderazgos y hechizos.',
    stats: { damagePct: 25, armourPct: 25 },
  },
  {
    slug: 'restoration',
    name: 'Restauración',
    tier: 1,
    position: 'C',
    kind: 'heal',
    description: 'Repara una estructura.',
  },
  {
    slug: 'skilled-healers',
    name: 'Sanadores expertos',
    tier: 1,
    position: 'R',
    kind: 'heal',
    description:
      'Cura parcialmente a las tropas elegidas y repone un hombre muerto por batallón.',
    stats: { menRestored: 1 },
  },
  {
    slug: 'lands-kept-safe',
    name: 'Tierras a salvo',
    tier: 2,
    position: 'LL',
    kind: 'summon',
    description:
      'Invoca una torre defensiva guarnecida con arqueros (con flechas de fuego si se ha investigado la mejora). Las tropas cercanas ganan +25 % de armadura.',
    stats: { armourPct: 25 },
  },
  {
    slug: 'garden-of-ithilien',
    name: 'Jardín de Ithilien',
    tier: 2,
    position: 'LR',
    kind: 'summon',
    description:
      'Un jardín frondoso en el campo de batalla: todas las tropas aliadas de dentro quedan ocultas y las enemigas pierden todo liderazgo. Lo habitan Montaraces de Ithilien.',
  },
  {
    slug: 'numenorean-engineering',
    name: 'Ingeniería númenóreana',
    tier: 2,
    position: 'RL',
    kind: 'summon',
    description:
      'Un trabuquete fijo donde se señale. Desde la 9.2.0 dura menos y es más frágil frente a espadas, pero alcanza objetivos más cercanos.',
  },
  {
    slug: 'sworn-allegiance',
    name: 'Lealtad jurada',
    tier: 2,
    position: 'RR',
    kind: 'buff',
    description:
      'Durante 60 s el Cuartel, el Campo de tiro y los Establos reclutan tropas de los feudos un 33 % más rápido y ya equipadas con Armas de la Ciudad Blanca.',
    stats: { durationS: 60, recruitSpeedPct: 33 },
  },
  {
    slug: 'oath-of-eorl',
    name: 'El Juramento de Eorl',
    tier: 3,
    position: 'L',
    kind: 'summon',
    description:
      'Tres batallones de Guerreros Rohirrim acuden en ayuda de Gondor durante 90 s.',
    stats: { battalions: 3, durationS: 90 },
  },
  {
    slug: 'western-winds',
    name: 'Vientos del Oeste',
    tier: 3,
    position: 'C',
    kind: 'utility',
    description:
      'Disipa Lluvia helada, Invierno blanco, Bendición de Ulmo, Oscuridad o Las luces se apagan; aturde a los enemigos y da +33 % de velocidad a todos los aliados del mapa.',
    stats: { speedPct: 33 },
  },
  {
    slug: 'dol-amroth-citadel',
    name: 'Ciudadela de Dol Amroth',
    tier: 3,
    position: 'R',
    kind: 'summon',
    description:
      'Levanta una Ciudadela de Dol Amroth (máximo dos), que recluta al príncipe Imrahil, a los Hombres de armas y a los Caballeros del Cisne.',
    stats: { maxCount: 2 },
  },
  {
    slug: 'messengers-of-manwe',
    name: 'Los Mensajeros de Manwë',
    tier: 4,
    position: 'L',
    kind: 'summon',
    description:
      'Gwaihir el Señor de los Vientos y tres Águilas gigantes, durante 75 s.',
    stats: { eagles: 3, durationS: 75 },
  },
  {
    slug: 'return-of-the-king',
    name: 'El Retorno del Rey',
    tier: 4,
    position: 'R',
    kind: 'summon',
    description:
      'Aragorn (Elessar) llega para quedarse, escoltado por cuatro Guardias Reales temporales. Las tropas cercanas al Rey son inmunes al miedo y al terror.',
    stats: { guards: 4, guardsDurationS: 120 },
  },
];

const gondor: FactionData = {
  code: 'gondor',
  heroes,
  units,
  structures,
  powers,
};

export { gondor };
