import {
  ab,
  type FactionData,
  type HeroData,
  type PowerData,
  type StructureData,
  type UnitData,
  up,
} from './types';

/**
 * Misty Mountains in Age of the Ring 9.2.0. Same sources and rules as
 * Gondor; the 9.3.0 fire-drake rework and Golfimbul's new model are
 * applied as a patch by the seed.
 */

const SCAVENGED_BLADES = up(
  'Hojas carroñeras',
  250,
  'C',
  'Más daño cuerpo a cuerpo. Se investiga en el Tesoro goblin (nivel 2).',
  null,
);
const SCAVENGED_ARMOUR = up(
  'Armadura carroñera',
  250,
  'T',
  'Reduce mucho el daño recibido. Se investiga en el Tesoro goblin (nivel 2).',
  null,
);
const BANNERS_OF_BOLG = up(
  'Estandartes de Bolg',
  100,
  'V',
  'El batallón sube a nivel 2 y repone bajas. Se investiga en el Tesoro goblin.',
  null,
  { levelGranted: 2 },
);
const FIRE_ARROWS = up(
  'Flechas de fuego',
  250,
  'C',
  'Mucho más daño con el arco. Se investiga en el Tesoro goblin.',
  null,
);
const MONSTROUS_RECOVERY = ab(
  'Recuperación monstruosa',
  3,
  null,
  'passive',
  'Recupera vida fuera de combate.',
);
const BOMBARD = ab(
  'Bombardeo',
  null,
  'W',
  'active',
  'Dispara sin parar sobre una zona.',
);
const WINTER_COAT = ab(
  'Pelaje de invierno',
  3,
  null,
  'passive',
  '+33 % de resistencia a las flechas.',
  { pierceResistPct: 33 },
);

const units: UnitData[] = [
  {
    slug: 'builder',
    name: 'Constructor',
    category: 'special',
    recruitedAt: 'Fortaleza',
    cost: 500,
    cp: 0,
    health: 625,
    armourSet: 'PorterArmor',
    weakAgainst: ['melee', 'ranged'],
    description:
      'Levanta todos los edificios. No ataca y cuesta 500; Lealtad salvaje lo abarata un 20 %.',
    abilities: [
      ab('Apagar fuego', null, null, 'active', 'Apaga incendios cercanos.'),
    ],
    images: { portrait: 'MM Porter Portrait.PNG' },
  },
  {
    slug: 'moria-orc-screechers',
    name: 'Chillones de Moria',
    category: 'swordsmen',
    recruitedAt: 'Cueva de orcos de Moria nivel 1',
    cost: 100,
    cp: 40,
    health: 50,
    armourSet: 'GoblinFighterArmor',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['numbers', 'pikemen'],
    weakAgainst: ['cavalry', 'monsters', 'elite'],
    description:
      'La marea. Baratísimos, rápidos y en hordas grandes: el núcleo del ejército hasta la mitad de la partida. Con varias cuevas salen sin parar, y a partir de 150 orcos de Moria juntos ganan +50 % de daño. Solos contra caballería, mueren.',
    abilities: [
      ab(
        'Hojas envenenadas',
        null,
        'W',
        'active',
        'Envenenan a quien golpean: daño continuado 15 s.',
        { durationS: 15 },
      ),
    ],
    upgrades: [BANNERS_OF_BOLG],
    stats: { swarmBonusDamagePct: 50, swarmThreshold: 150 },
    images: {
      portrait: 'Moria Screecher Portrait.PNG',
      ingame: 'Screechers.png',
    },
  },
  {
    slug: 'moria-orc-archers',
    name: 'Arqueros de Moria',
    category: 'archers',
    recruitedAt: 'Cueva de orcos de Moria nivel 1',
    cost: 250,
    cp: 60,
    health: 100,
    armourSet: 'GoblinArcherArmor',
    attackType: 'A distancia, un objetivo',
    strongAgainst: ['ranged'],
    weakAgainst: ['cavalry', 'siege'],
    description:
      'Los arqueros que mataron a Balin. Frágiles, pero sus Flechas envenenadas a la vez desde varios batallones tumban casi cualquier cosa, y hacen un 55 % más de daño a monstruos. Con Brutos delante.',
    abilities: [
      BOMBARD,
      ab(
        'Flechas envenenadas',
        null,
        'R',
        'active',
        'Daño continuado 15 s; +55 % de daño contra monstruos.',
        { durationS: 15, damagePctVsMonsters: 55 },
      ),
    ],
    upgrades: [FIRE_ARROWS, BANNERS_OF_BOLG],
    images: {
      portrait: 'Moria Archer Portrait.PNG',
      ingame: 'Moria Archers.png',
    },
  },
  {
    slug: 'goblin-town-warriors',
    name: 'Guerreros de Ciudad de los Trasgos',
    category: 'swordsmen',
    recruitedAt: 'Tótem del enjambre (Gran Trasgo)',
    requirements: 'El Gran Trasgo planta un tótem',
    cost: 85,
    cp: 40,
    health: 60,
    armourSet: 'GoblinFighterArmor',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['numbers', 'pikemen'],
    weakAgainst: ['cavalry', 'monsters', 'elite'],
    description:
      'Los adoradores del Gran Gordo. La unidad de spam definitiva: 85 de coste, horda enorme y reclutamiento fugaz. Carne de cañón para proteger a las unidades caras; roban recursos y desgastan edificios al pegarles.',
    abilities: [
      ab(
        'Manos sucias',
        null,
        null,
        'passive',
        'Cada golpe a una estructura le quita un 5 % de armadura y roba recursos.',
        { structureArmourReductionPct: 5 },
      ),
    ],
    upgrades: [BANNERS_OF_BOLG],
    images: {
      portrait: 'Goblin Town Portrait.PNG',
      ingame: 'Goblin Towners.png',
    },
  },
  {
    slug: 'mountain-orc-slashers',
    name: 'Tajadores de las Montañas',
    category: 'swordsmen',
    recruitedAt: 'Refugio de orcos de las Montañas nivel 1',
    cost: 375,
    cp: 60,
    health: 250,
    armourSet: 'SoldierArmor',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['pikemen'],
    weakAgainst: ['cavalry', 'monsters'],
    description:
      'Orcos de las montañas unidos por Azog: la espada "normal" de la facción, la que aguanta un choque sin necesitar superioridad numérica. Mejorables del todo y con el liderazgo de Muzgash sirven hasta la partida tardía.',
    abilities: [
      ab(
        'Terror de la Montaña',
        2,
        null,
        'passive',
        'Cada golpe seguido suma +5 % de daño, hasta +25 %.',
        { damagePctPerHit: 5, damagePctMax: 25 },
      ),
    ],
    upgrades: [SCAVENGED_ARMOUR, SCAVENGED_BLADES, BANNERS_OF_BOLG],
    images: { portrait: 'Slashers Portrait.PNG', ingame: 'Slashers.png' },
  },
  {
    slug: 'mountain-orc-brutes',
    name: 'Brutos de las Montañas',
    category: 'pikemen',
    recruitedAt: 'Refugio de orcos de las Montañas nivel 1',
    cost: 375,
    cp: 60,
    health: 270,
    armourSet: 'PikemenArmor',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['cavalry', 'monsters', 'heroes'],
    weakAgainst: ['swordsmen'],
    description:
      'Las únicas picas hasta los Berserkers: imprescindibles, porque todo lo barato de la facción muere ante la caballería. Su puercoespín da +75 % de armadura.',
    abilities: [
      ab(
        'Formación puercoespín',
        null,
        'W',
        'formation',
        'Círculo de picas. No se mueven y ganan +75 % de armadura.',
        { armourPct: 75 },
      ),
    ],
    upgrades: [SCAVENGED_ARMOUR, SCAVENGED_BLADES, BANNERS_OF_BOLG],
    images: { portrait: 'Brutes Portrait.PNG', ingame: 'Brutes.png' },
  },
  {
    slug: 'mountain-orc-scouts',
    name: 'Exploradores de las Montañas',
    category: 'archers',
    recruitedAt: 'Refugio de orcos de las Montañas nivel 2',
    cost: 350,
    cp: 60,
    health: 200,
    armourSet: 'ArcherArmor',
    attackType: 'A distancia, un objetivo',
    strongAgainst: ['ranged', 'monsters', 'flying'],
    weakAgainst: ['cavalry', 'siege'],
    description:
      'Cazadores de hombres, mucho mejores arqueros que los de Moria. Completamente mejorables se acercan a los arqueros de élite de otras facciones; sus Flechas de púas castigan a monstruos y voladores.',
    abilities: [
      BOMBARD,
      ab(
        'Flechas de púas',
        2,
        'R',
        'active',
        'Durante 20 s, +65 % de daño a monstruos y voladores, que además pierden un 25 % de velocidad.',
        { durationS: 20, damagePctVsMonsters: 65, targetSpeedPct: -25 },
      ),
    ],
    upgrades: [SCAVENGED_ARMOUR, FIRE_ARROWS, BANNERS_OF_BOLG],
    images: { portrait: 'Orc Scout Portrait.PNG', ingame: 'Orc Scouts.png' },
  },
  {
    slug: 'gundabad-berserkers',
    name: 'Berserkers de Gundabad',
    category: 'special',
    recruitedAt: 'Refugio de orcos de las Montañas nivel 3',
    cost: 800,
    cp: 90,
    health: 600,
    armourSet: 'GundabadBerserkerHeavyArmor',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['swordsmen', 'cavalry', 'heroes'],
    weakAgainst: ['archers', 'heroic'],
    description:
      'Los orcos pálidos de Azog: la mejor infantería no heroica de la facción. Llevan armadura pesada de serie y mezclan espadas y picas en el mismo batallón, así que aguantan a infantería y caballería.',
    abilities: [
      ab(
        'Muro de lanzas',
        null,
        'W',
        'formation',
        '+40 % de armadura, resistencia a la carga y más daño a caballería; -33 % de velocidad.',
        { armourPct: 40, speedPct: -33 },
      ),
      ab(
        'Determinación cruel',
        2,
        'R',
        'active',
        '+33 % de daño y resistencia al empuje durante 20 s.',
        { damagePct: 33, durationS: 20 },
      ),
    ],
    upgrades: [SCAVENGED_BLADES, BANNERS_OF_BOLG],
    images: {
      portrait: 'Gundabad Berserker Portrait.PNG',
      ingame: 'Gundabad Berserkers.png',
    },
  },
  {
    slug: 'bolgs-bodyguard',
    name: 'Guardia de Bolg',
    category: 'heroic',
    recruitedAt: 'Refugio de orcos de las Montañas nivel 3',
    requirements: 'Segundo batallón: mejora Agujas de Gundabad',
    cost: 1500,
    cp: 100,
    health: 800,
    maxCount: 2,
    armourSet: 'BodyGuardArmor',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['infantry', 'cavalry', 'heroes'],
    weakAgainst: ['archers'],
    description:
      'Los orcos más grandes y crueles, los que mataron a Thorin. La unidad heroica: mucha vida y daño, cazan héroes (a los que debilitan solo con estar cerca) y con nivel se vuelven una máquina.',
    abilities: [
      ab(
        'Intimidación',
        null,
        null,
        'passive',
        'Los héroes y unidades heroicas enemigas cercanas pierden un 20 % de daño y un 15 % de armadura.',
        { enemyDamagePct: -20, enemyArmourPct: -15 },
      ),
      ab(
        'Lanzar cráneo',
        3,
        'R',
        'active',
        'Un proyectil potente con daño en área.',
      ),
      ab(
        'Resolución oscura',
        7,
        'T',
        'active',
        '+100 % de daño a cambio de -25 % de armadura durante 20 s.',
        { damagePct: 100, armourPct: -25, durationS: 20 },
      ),
    ],
    images: {
      portrait: 'Horrors of Gram Portrait.PNG',
      ingame: 'Horrors of Gram.png',
    },
  },
  {
    slug: 'warg-pack',
    name: 'Manada de wargos',
    category: 'cavalry',
    recruitedAt: 'Túmulo de lobos nivel 1',
    cost: 325,
    cp: 40,
    health: 250,
    armourSet: 'WargPackArmor',
    attackType: 'Cuerpo a cuerpo y carga',
    strongAgainst: ['swordsmen', 'archers'],
    weakAgainst: ['pikemen'],
    description:
      'La caballería temprana: barata, rápida, para emboscar arqueros y golpear la economía. Aullar antes de la carga la hace mucho más letal; Golfimbul la mejora aún más.',
    abilities: [
      ab(
        'Aullido',
        null,
        'W',
        'active',
        '+25 % de daño y +25 % de armadura durante 45 s.',
        { damagePct: 25, armourPct: 25, durationS: 45 },
      ),
      WINTER_COAT,
    ],
    upgrades: [
      up('Alfa de la manada', null, null, 'Un wargo alfa lidera la manada.'),
    ],
    images: { portrait: 'Wargs Portrait.PNG', ingame: 'MM Wargs.png' },
  },
  {
    slug: 'gundabad-wolf-riders',
    name: 'Jinetes de lobo de Gundabad',
    category: 'cavalry',
    recruitedAt: 'Túmulo de lobos nivel 2',
    cost: 550,
    cp: 80,
    health: 375,
    armourSet: 'WargHeavyArmor',
    attackType: 'Cuerpo a cuerpo y carga',
    strongAgainst: ['swordsmen', 'archers'],
    weakAgainst: ['pikemen', 'monsters'],
    description:
      'Los cazadores que persiguieron a Thorin por Eriador. La caballería estándar, con más vida y armadura que los wargos sueltos. Para golpes de ida y vuelta y flanqueos.',
    abilities: [
      ab(
        'Aullido',
        null,
        'W',
        'active',
        '+33 % de daño y +33 % de armadura durante 45 s.',
        { damagePct: 33, armourPct: 33, durationS: 45 },
      ),
      WINTER_COAT,
    ],
    upgrades: [SCAVENGED_BLADES, BANNERS_OF_BOLG],
    images: {
      portrait: 'MM Riders Portrait.PNG',
      ingame: 'MM Warg Riders.png',
    },
  },
  {
    slug: 'white-wolves',
    name: 'Lobos blancos',
    category: 'cavalry',
    recruitedAt: 'Ruina de Angmar',
    requirements: 'Poder Ruina de Angmar (10 PP)',
    cost: 750,
    cp: 80,
    health: 500,
    armourSet: 'WargPackArmor',
    attackType: 'Cuerpo a cuerpo y carga',
    strongAgainst: ['swordsmen', 'archers'],
    weakAgainst: ['pikemen'],
    description:
      'Los lobos del Invierno Cruel. Caballería de élite: más vida que los wargos y un aullido que aterroriza al enemigo 10 s. Golfimbul también los invoca sueltos.',
    abilities: [
      ab(
        'Aullido',
        3,
        'W',
        'active',
        'Un aullido que aterroriza a los enemigos cercanos 10 s.',
        { durationS: 10 },
      ),
      WINTER_COAT,
    ],
    upgrades: [
      up('Alfa de la manada', null, null, 'Un lobo alfa lidera la manada.'),
    ],
    images: {
      portrait: 'White Wolves Portrait.PNG',
      ingame: 'White Wolves.png',
    },
  },
  {
    slug: 'dead-of-arnor',
    name: 'Muertos de Arnor',
    category: 'swordsmen',
    recruitedAt: 'Ruina de Angmar',
    requirements: 'Poder Ruina de Angmar (10 PP)',
    cost: 300,
    cp: 48,
    health: 200,
    armourSet: 'RisenDead',
    attackType: 'Cuerpo a cuerpo',
    strongAgainst: ['pikemen'],
    weakAgainst: ['cavalry', 'monsters'],
    description:
      'Espíritus de Angmar en cuerpos de soldados de Arthedain. Infantería rápida que se regenera y repone bajas fuera de combate: acosan, se retiran y vuelven llenos.',
    abilities: [
      ab(
        'Sustento oscuro',
        null,
        null,
        'passive',
        'Recuperan vida y reponen bajas rápido fuera de combate.',
      ),
      ab(
        'Toque de ruina',
        2,
        'R',
        'active',
        'Durante 20 s cada golpe quita un 10 % de armadura.',
        { armourReductionPct: 10, durationS: 20 },
      ),
    ],
    images: {
      portrait: 'Dead of Arnor Portrait.PNG',
      ingame: 'Dead of Arnor.png',
    },
  },
  {
    slug: 'cave-troll',
    name: 'Trol de las cavernas',
    category: 'monster',
    recruitedAt: 'Guarida de troles nivel 1',
    cost: 500,
    cp: 45,
    health: 2500,
    armourSet: 'CaveTrollArmor',
    attackType: 'Cuerpo a cuerpo o rocas, en área',
    strongAgainst: ['swordsmen', 'structures'],
    weakAgainst: ['pikemen', 'archers'],
    description:
      'Los troles atormentados de Moria. Sustituyen al asedio tradicional: tiran rocas, arrancan árboles y lanzan orcos que aterrorizan al caer. Barato para lo que aguanta.',
    abilities: [
      ab(
        'Golpear o tirar rocas',
        null,
        'W',
        'toggle',
        'Alterna cuerpo a cuerpo y rocas.',
      ),
      ab('Bombardeo', null, 'R', 'active', 'Rocas sobre una zona.'),
      ab(
        'Coger un orco',
        null,
        'T',
        'active',
        'Coge un orco y lo lanza; donde cae, el enemigo se aterroriza.',
      ),
      ab('Buscar un árbol', null, 'C', 'active', 'Arranca un árbol como arma.'),
      MONSTROUS_RECOVERY,
    ],
    images: { portrait: 'Cave Troll Portrait.PNG', ingame: 'CaveTroll.png' },
  },
  {
    slug: 'snow-trolls',
    name: 'Troles de las nieves',
    category: 'monster',
    recruitedAt: 'Guarida de troles nivel 2',
    cost: 850,
    cp: 80,
    health: 720,
    armourSet: 'SnowTrollNewArmor',
    attackType: 'Lanzas a distancia o cuerpo a cuerpo con empuje',
    strongAgainst: ['infantry', 'monsters'],
    weakAgainst: ['pikemen'],
    description:
      'Batallones de cinco troles que lanzan lanzas: daño alto a distancia, único entre los monstruos, ideal contra tropas de élite. Cuerpo a cuerpo son más vulnerables.',
    abilities: [
      BOMBARD,
      ab(
        'Cuerpo a cuerpo o lanzas',
        null,
        'R',
        'toggle',
        'Alterna los dos modos.',
      ),
      ab(
        'Furia trol',
        2,
        'W',
        'active',
        'Lanzan con toda su fuerza: más daño y derriban en un radio grande.',
      ),
      MONSTROUS_RECOVERY,
    ],
    stats: { battalionSize: 5 },
    images: { portrait: 'Snow Troll Portrait.PNG', ingame: 'SnowTrolls.png' },
  },
  {
    slug: 'giant-bat',
    name: 'Murciélago gigante',
    category: 'monster',
    recruitedAt: 'Guarida de troles nivel 2',
    cost: 700,
    cp: 50,
    health: 1500,
    armourSet: 'GiantBatArmor',
    attackType: 'Cuerpo a cuerpo en área (volador)',
    strongAgainst: ['infantry', 'cavalry', 'siege'],
    weakAgainst: ['archers'],
    description:
      'Los murciélagos vampiro de Bolg. Voladores rápidos que la infantería y la caballería no pueden tocar: acosan la economía y neutralizan ejércitos sin arqueros. Con arqueros delante, no.',
    abilities: [
      ab(
        'Vampirismo',
        null,
        null,
        'passive',
        'Los voladores enemigos golpeados pierden un 30 % de velocidad 5 s. A nivel 3 recupera vida con cada golpe.',
        { targetSpeedPct: -30, durationS: 5 },
      ),
      MONSTROUS_RECOVERY,
    ],
    images: { portrait: 'Cave Bat Portrait.PNG', ingame: 'Bat.png' },
  },
  {
    slug: 'gundabad-stone-troll',
    name: 'Trol de piedra de Gundabad',
    category: 'monster',
    recruitedAt: 'Guarida de troles nivel 3',
    cost: 1000,
    cp: 90,
    health: 3000,
    armourSet: 'AttackTrollArmor',
    attackType: 'Cuerpo a cuerpo en área',
    strongAgainst: ['cavalry', 'swordsmen', 'structures'],
    weakAgainst: ['archers', 'pikemen'],
    description:
      'El trol más poderoso de la facción, y el más caro de completar: tres mejoras de 500 que lo blindan, lo enfurecen y lo hacen más lento. Completo, derriba edificios, caballería e infantería por igual.',
    abilities: [
      ab(
        'Cráneo duro',
        2,
        'W',
        'active',
        'Durante 15 s, +50 % de daño a estructuras y -50 % de armadura; sin daño en área contra edificios.',
        { structureDamagePct: 50, armourPct: -50, durationS: 15 },
      ),
      MONSTROUS_RECOVERY,
    ],
    upgrades: [
      up(
        'Yelmo temible',
        500,
        'R',
        'Mucha más armadura y asusta a los enemigos. -7 % de velocidad.',
        null,
        { speedPct: -7 },
      ),
      up(
        'Armadura dentada',
        500,
        'T',
        'Muchos más puntos de vida y arrolla mejor. -7 % de velocidad.',
        null,
        { speedPct: -7 },
      ),
      up(
        'Guanteletes de guadaña',
        500,
        'C',
        'Mucho más daño y daño en área. -7 % de velocidad.',
        null,
        { speedPct: -7 },
      ),
    ],
    images: { portrait: 'Stone Troll Portrait.PNG', ingame: 'StoneTroll.png' },
  },
  {
    slug: 'mountain-giant',
    name: 'Gigante de las Montañas',
    category: 'monster',
    recruitedAt: 'Guarida de troles nivel 3',
    cost: 900,
    cp: 60,
    health: 3400,
    maxCount: 2,
    armourSet: 'MountainGiantArmor',
    attackType: 'Cuerpo a cuerpo o rocas de asedio',
    strongAgainst: ['structures', 'infantry', 'cavalry'],
    weakAgainst: ['pikemen', 'archers'],
    description:
      'Los gigantes que Bilbo vio tirarse rocas en la tormenta. Alternan rocas de largo alcance y pisotones que despejan todo alrededor. Máximo dos, cinco con Prole del Norte.',
    abilities: [
      ab('Cambiar ataque', null, 'W', 'toggle', 'Rocas o cuerpo a cuerpo.'),
      ab('Bombardeo', null, 'R', 'active', 'Rocas sobre una zona.'),
      ab(
        'Pisotón',
        null,
        'R',
        'active',
        'Cuerpo a cuerpo: un golpe con daño extra que derriba alrededor.',
      ),
      MONSTROUS_RECOVERY,
    ],
    stats: { maxCountWithBrood: 5 },
    images: {
      portrait: 'Mountain Giant Portrait.PNG',
      ingame: 'Giant Melee.png',
    },
  },
  {
    slug: 'fire-wyrm',
    name: 'Dragón de fuego',
    category: 'monster',
    recruitedAt: 'Guarida de wyrms nivel 1',
    requirements: 'Mejora Prole del Norte en la Fortaleza',
    cost: 1400,
    cp: 50,
    health: 3500,
    maxCount: 2,
    armourSet: 'FireDrakeArmor',
    attackType: 'Aliento de fuego en área',
    strongAgainst: ['infantry', 'structures'],
    weakAgainst: ['archers', 'pikemen', 'fire'],
    description:
      'Wyrms sin alas de los Yermos del Norte que escupen fuego. Caros, limitados y lentos, pero barren hordas y queman bases. Máximo dos, cuatro con Prole del Norte.',
    abilities: [
      ab(
        'Aliento de fuego',
        null,
        'W',
        'active',
        'Escupe fuego en un cono; arrasa infantería apelotonada y edificios.',
      ),
      MONSTROUS_RECOVERY,
    ],
    stats: { maxCountWithBrood: 4 },
    images: { portrait: 'Wyrm Portrait.PNG', ingame: 'Wyrm.png' },
  },
  {
    slug: 'cold-drake',
    name: 'Dragón frío',
    category: 'monster',
    recruitedAt: 'Guarida de wyrms nivel 2',
    requirements: 'Mejora Prole del Norte en la Fortaleza',
    cost: 2000,
    cp: 80,
    health: 6000,
    maxCount: 1,
    armourSet: 'ColdDrakeArmor',
    attackType: 'Cuerpo a cuerpo en área con empuje (volador)',
    strongAgainst: ['infantry', 'cavalry', 'structures'],
    weakAgainst: ['archers'],
    description:
      'Un dragón sin fuego pero con alas. Solo uno, detrás de Prole del Norte y 2000 de coste; aguanta muchísimo más que un murciélago y rompe cualquier línea. Los arqueros mejorados son su único problema.',
    abilities: [
      ab(
        'Rugido que hiela el corazón',
        2,
        'W',
        'active',
        'Paraliza a los enemigos cercanos.',
      ),
      MONSTROUS_RECOVERY,
    ],
    images: { portrait: 'Cold Drake Portrait.png', ingame: 'Cold Drake.png' },
  },
  {
    slug: 'cave-troll-destroyer',
    name: 'Trol destructor',
    category: 'monster',
    recruitedAt: 'Túnel orco (poder ¡Ya vienen!)',
    requirements: 'Poder ¡Ya vienen! (10 PP)',
    cost: 1150,
    cp: 80,
    health: 3000,
    armourSet: 'CaveTrollArmor',
    attackType: 'Cuerpo a cuerpo en área',
    strongAgainst: ['swordsmen', 'structures'],
    weakAgainst: ['pikemen', 'archers'],
    description:
      'El trol de las cavernas más grande y más torturado: el Olog-hai de la facción. Aparece con el poder ¡Ya vienen! y no consume puntos de mando. Puede robar un trol enemigo.',
    abilities: [
      ab(
        'Dominar trol',
        2,
        'W',
        'active',
        'Toma el control de un trol enemigo.',
      ),
      MONSTROUS_RECOVERY,
    ],
    images: {
      portrait: 'Cave-troll Destroyer Portrait.png',
      ingame: 'Cave-troll Destroyer In Game.png',
    },
  },
  {
    slug: 'watcher-in-the-water',
    name: 'Vigilante del Agua',
    category: 'monster',
    recruitedAt: 'Poder Invocar al Vigilante (15 PP)',
    isSummon: true,
    health: 5000,
    armourSet: 'WatcherArmor',
    attackType: 'Tentáculos en área',
    strongAgainst: ['infantry', 'cavalry'],
    weakAgainst: ['archers'],
    description:
      'Sale del suelo 30 s, derribando a todo lo que hay encima, y azota con los tentáculos a cualquiera que se acerque, amigo o enemigo. Tapa un paso estrecho o revienta un asedio; se regenera devorando.',
    stats: { durationS: 30 },
    images: { portrait: 'Watcher Portrait.PNG', ingame: 'Watcher ingame.png' },
  },
];

const heroes: HeroData[] = [
  {
    slug: 'golfimbul',
    name: 'Golfimbul',
    title: 'Cacique del Monte Gram',
    recruitedAt: 'Fortaleza',
    cost: 1400,
    buildTime: 30,
    health: 2300,
    armourSet: 'HeroArmorMounted',
    attackType: 'Cuerpo a cuerpo, siempre montado',
    description:
      'Descendiente del Golfimbul cuya cabeza inventó el golf. Va siempre montado y es el héroe de la caballería: su liderazgo da daño, velocidad y experiencia a wargos y lobos, invoca Lobos blancos y a nivel 8 lanza una carga gloriosa.',
    abilities: [
      ab(
        'Cacique del Monte Gram',
        null,
        null,
        'leadership',
        'Wargos y caballería cercanos: +25 % de daño, +15 % de velocidad y +50 % de experiencia.',
        { damagePct: 25, speedPct: 15, xpPct: 50 },
      ),
      ab(
        'Lobos blancos de Forochel',
        3,
        'R',
        'active',
        'Invoca 3 Lobos blancos (6 a partir del nivel 6).',
        { wolves: 3, wolvesAt6: 6 },
      ),
      ab(
        'Odio a la Hermosa Gente',
        8,
        'T',
        'active',
        'Él y los lobos, wargos y jinetes cercanos ganan +50 % de daño, +50 % de armadura y cargan sin frenar 20 s.',
        { damagePct: 50, armourPct: 50, durationS: 20 },
      ),
    ],
    images: { portrait: 'Golfimbul.png', ingame: 'Golfimbul ingame.png' },
  },
  {
    slug: 'muzgash',
    name: 'Muzgash',
    title: 'Veterano legendario',
    recruitedAt: 'Fortaleza',
    cost: 1300,
    buildTime: 40,
    health: 2300,
    armourSet: 'HeroArmor',
    attackType: 'Cuerpo a cuerpo',
    description:
      'Un cacique con una lanza enana robada, veterano de la Guerra de Enanos y Orcos. Liderazgo temprano para los orcos, que crece con el nivel y acaba dando recursos por muerte: es lo que mantiene útiles a los orcos de Moria y de las montañas en la partida larga.',
    abilities: [
      ab(
        'Veterano legendario',
        1,
        null,
        'leadership',
        'Orcos de Moria y de las montañas cercanos: +15 % de daño y armadura; +33 % a partir del nivel 8, cuando además ganan recursos por cada muerte.',
        { damagePct: 15, armourPct: 15, damagePctAt8: 33 },
      ),
      ab(
        'Hoja pútrida',
        3,
        'R',
        'active',
        'Durante 20 s su lanza envenena, hace daño en área y empuja.',
        { durationS: 20 },
      ),
      ab(
        'Disciplina de hierro',
        6,
        'T',
        'active',
        'Sus tropas ganan +25 % de velocidad durante 30 s.',
        { speedPct: 25, durationS: 30 },
      ),
      ab(
        'Trofeo de supremacía',
        9,
        'C',
        'active',
        'Los enemigos de la zona pierden todo liderazgo y un 33 % de velocidad.',
        { enemySpeedPct: -33 },
      ),
    ],
    images: { portrait: 'Muzgash.PNG', ingame: 'Muzgash ingame.png' },
  },
  {
    slug: 'urshak',
    name: 'Urshak',
    title: 'Brujo de Moria',
    recruitedAt: 'Fortaleza',
    cost: 1600,
    buildTime: 50,
    health: 2500,
    armourSet: 'HeroArmor',
    attackType: 'Cuerpo a cuerpo',
    description:
      'El orco de Moria que persiguió a la Compañía hasta Lórien. Pelea mal y hechiza bien: debilita a todo lo que le rodea, derrumba edificios, congela batallas y a nivel 10 pone a los enemigos a pelear entre sí.',
    abilities: [
      ab(
        'Intimidación',
        null,
        'W',
        'leadership',
        'Troles, murciélagos y gigantes cercanos: +15 % de velocidad y visión. Enemigos cercanos: -15 % de daño y -10 % de armadura (-25 %, -20 % y -10 % de velocidad a nivel 5).',
        { enemyDamagePct: -15, enemyArmourPct: -10, monsterSpeedPct: 15 },
      ),
      ab(
        'Derrumbe',
        3,
        'R',
        'active',
        'Un edificio enemigo sufre mucho daño y queda inutilizado 20 s. Abre puertas.',
        { durationS: 20 },
      ),
      ab(
        'Invierno cruel',
        6,
        'T',
        'active',
        'Todas las tropas de la zona, propias y ajenas, quedan congeladas 15 s.',
        { durationS: 15 },
      ),
      ab(
        'El Pozo Negro',
        8,
        'C',
        'active',
        'Daño continuado a los enemigos de la zona y curación a los aliados.',
      ),
      ab(
        'Profecía oscura',
        10,
        'V',
        'active',
        'Las tropas elegidas se vuelven hostiles entre sí.',
      ),
    ],
    images: { portrait: 'Urshak.png', ingame: 'Urshak ingame.png' },
  },
  {
    slug: 'lug-the-mauled',
    name: 'Lug el Mutilado',
    title: 'Asesino a sueldo',
    recruitedAt: 'Fortaleza',
    cost: 1800,
    buildTime: 60,
    health: 2500,
    armourSet: 'HeroArmor',
    attackType: 'Espada o cuchillos arrojadizos',
    description:
      'Un psicópata a sueldo que siempre atrapa a su hombre. Cazador de héroes: pone precio a una cabeza, alterna espada y cuchillos, y sus dos grandes habilidades le hacen daño a él mismo. Poco daño por golpe pero muy rápido.',
    abilities: [
      ab('Cambiar de arma', 1, 'W', 'toggle', 'Espada o cuchillos.'),
      ab(
        'Cazarrecompensas',
        1,
        'R',
        'active',
        'Un héroe enemigo pierde armadura y velocidad 20 s: 20 % (30 % a nivel 3, 40 % a nivel 6, 50 % a nivel 10).',
        { targetArmourPct: -20, targetArmourPctAt10: -50, durationS: 20 },
      ),
      ab(
        'Caer luchando',
        3,
        'T',
        'active',
        'Se hiere para ganar +50 % de armadura, +50 % de daño y +30 % de velocidad 20 s. Solo con espada.',
        { armourPct: 50, damagePct: 50, speedPct: 30, durationS: 20 },
      ),
      ab(
        'Tierra quemada',
        6,
        'C',
        'active',
        'Prende fuego al suelo y quema a todos, amigos y enemigos.',
      ),
    ],
    images: { portrait: 'Lug Portrait.png', ingame: 'Lug Sword.png' },
  },
  {
    slug: 'great-goblin',
    name: 'El Gran Trasgo',
    title: 'Rey de Ciudad de los Trasgos',
    recruitedAt: 'Fortaleza',
    cost: 2400,
    buildTime: 60,
    health: 2400,
    armourSet: 'GreatGoblinArmor',
    attackType: 'Cuerpo a cuerpo en área',
    description:
      'El que quiso matar a Thorin por llevar a Orcrist. El héroe del spam: planta tótems que reclutan Guerreros de Ciudad de los Trasgos, da liderazgo y resistencia al miedo a orcos y trasgos, y con nivel invoca hordas y canta una canción que hunde al rival.',
    abilities: [
      ab(
        'Exigencia del Rey Trasgo',
        1,
        'W',
        'active',
        'Planta un Tótem del enjambre (máximo 3) que recluta Guerreros de Ciudad de los Trasgos y revela sigilo.',
        { maxTotems: 3 },
      ),
      ab(
        'El Rey Trasgo',
        1,
        'R',
        'leadership',
        'Orcos de Moria y trasgos cercanos: +33 % de daño, +33 % de armadura y resistencia al miedo. A nivel 7 da mucha experiencia a un batallón.',
        { damagePct: 33, armourPct: 33 },
      ),
      ab(
        'Enjambre',
        4,
        'T',
        'active',
        'Invoca tres hordas de trasgos (una más por nivel) y da +15 % de daño a orcos y trasgos cercanos 20 s.',
        { hordes: 3, damagePct: 15, durationS: 20 },
      ),
      ab(
        'Anticuario',
        7,
        'C',
        'active',
        'Hace un trato con antigüedades. Puede quemarse; ojo con el mal del dragón.',
      ),
      ab(
        'Canción abominable',
        9,
        'V',
        'active',
        'Aliados cercanos: +33 % de daño y armadura 30 s. Enemigos: -25 % de daño, -20 % de armadura y sin liderazgo.',
        { damagePct: 33, armourPct: 33, enemyDamagePct: -25, durationS: 30 },
      ),
    ],
    images: { portrait: 'GreatGoblin.PNG', ingame: 'GG ingame.png' },
  },
  {
    slug: 'bolg-of-the-north',
    name: 'Bolg del Norte',
    title: 'Señor de Gundabad',
    recruitedAt: 'Fortaleza',
    cost: 3500,
    buildTime: 80,
    health: 3300,
    armourSet: 'ToughHeroArmor',
    attackType: 'Cuerpo a cuerpo en área',
    description:
      'El hijo de Azog, el que hirió de muerte a Thorin. El líder de la facción: liderazgo de +50 % de armadura y resistencia al miedo para orcos, wargos y murciélagos, un odio a los enanos que crece con cada golpe y, a nivel 10, un ejército invocado.',
    abilities: [
      ab(
        'Señor salvaje',
        null,
        null,
        'leadership',
        'Orcos, wargos y murciélagos cercanos: +50 % de armadura y experiencia, resistencia al miedo y al terror.',
        { armourPct: 50, xpPct: 50 },
      ),
      ab(
        'Odio creciente',
        null,
        'R',
        'active',
        'Pasiva: más daño contra enanos. Activa: empuja con más alcance 30 s; a nivel 3 cada golpe seguido suma +10 % de daño hasta +50 %.',
        { durationS: 30, damagePctPerHit: 10, damagePctMax: 50 },
      ),
      ab(
        'Gobernado por el miedo',
        4,
        'T',
        'active',
        'Aliados cercanos: +125 % de daño, -50 % de armadura y sin experiencia 20 s. Los enemigos cercanos se acobardan 15 s.',
        { damagePct: 125, armourPct: -50, durationS: 20 },
      ),
      ab(
        'Filas impenetrables',
        7,
        'C',
        'active',
        'Cuatro guardaespaldas lo protegen. Activa: +50 % de armadura 30 s.',
        { armourPct: 50, durationS: 30, bodyguards: 4 },
      ),
      ab(
        'Terror del Norte',
        10,
        'V',
        'active',
        'Invoca un pequeño ejército de orcos de las montañas, jinetes de lobo y murciélagos.',
      ),
    ],
    images: {
      portrait: 'Bolg Portrait.png',
      ingame: 'Bolg of the North ingame.png',
    },
  },
  {
    slug: 'smaug',
    name: 'Smaug',
    title: 'El Terrible',
    recruitedAt: 'Fortaleza (con el Anillo Único)',
    cost: 10000,
    buildTime: 80,
    health: 12100,
    armourSet: 'DrogothArmor',
    attackType: 'Fuego en área, volando o en tierra',
    description:
      'El último gran dragón, héroe del Anillo de la facción. Diez mil de coste (menos con Lealtad salvaje) y lo cambia todo: volando solo lo tocan los arqueros, en tierra paraliza héroes, y el Mal del dragón pone al rival a pelear consigo mismo.',
    abilities: [
      ab('Aterrizar o despegar', null, 'W', 'toggle', 'Vuela o va a pie.'),
      ab(
        'Alas de huracán',
        null,
        'R',
        'active',
        'Volando: onda de choque bajo Smaug que derriba y daña.',
      ),
      ab(
        'Mirada temible',
        null,
        'R',
        'active',
        'En tierra: paraliza a un héroe enemigo un rato.',
      ),
      ab(
        'Espíritu ígneo',
        null,
        'T',
        'active',
        'Un misil de fuego contra un objetivo.',
      ),
      ab('Yo soy la muerte', null, 'C', 'active', 'Fuego sobre una zona.'),
      ab(
        'Mal del dragón',
        null,
        'V',
        'active',
        'Las tropas elegidas se vuelven hostiles entre sí.',
      ),
    ],
    images: { portrait: 'Smaug.PNG', ingame: 'Smaug ingame.png' },
  },
  {
    slug: 'durins-bane',
    name: 'Daño de Durin',
    title: 'Balrog de Morgoth',
    recruitedAt: 'Poder Daño de Durin (25 PP)',
    isSummon: true,
    health: 5800,
    armourSet: 'BalrogArmor',
    attackType: 'Cuerpo a cuerpo en área',
    description:
      'El Balrog de Moria durante 100 s. Fuego, látigo y espada: arrasa ejércitos y bases mientras dura.',
    abilities: [
      ab('Prender', null, 'W', 'active', 'Se envuelve en llamas.'),
      ab(
        'Látigo',
        null,
        'R',
        'active',
        'Un latigazo de fuego que daña en área.',
      ),
      ab('Rugido', null, 'T', 'active', 'Aterroriza a los enemigos cercanos.'),
    ],
    stats: { durationS: 100 },
    images: { portrait: 'Balrog Portrait.png', ingame: 'Balrog ingame.png' },
  },
  {
    slug: 'were-worm',
    name: 'Gusano',
    title: 'Devorador de la tierra',
    recruitedAt: 'Poder Invocar Gusano (15 PP)',
    isSummon: true,
    health: 7500,
    armourSet: 'SummonedWyrmArmor',
    attackType: 'Aliento de fuego en área',
    description:
      'Sale de la tierra donde se señale durante 60 s, con un túnel conectado a la red propia para traer refuerzos o escapar. Apenas se mueve, pero su fuego derrite tropas apiñadas y edificios.',
    abilities: [
      ab(
        'Reposicionar',
        null,
        'W',
        'active',
        'Se desplaza a otro punto cercano.',
      ),
    ],
    stats: { durationS: 60 },
    images: { portrait: 'Were-wyrm Portrait.png', ingame: 'Were-worm.png' },
  },
];

const structures: StructureData[] = [
  {
    slug: 'fortress',
    name: 'Fortaleza de las Montañas Nubladas',
    kind: 'fortress',
    cost: 5000,
    buildTime: 120,
    health: 7500,
    armourSet: 'FortressArmor',
    description:
      'Gundabad. Recluta constructores y todos los héroes, dispara, produce 25 recursos por ciclo y se conecta a la red de túneles. Lealtad salvaje, su mejora clave, captura guaridas neutrales y abarata héroes.',
    produces: ['Constructor'],
    upgrades: [
      up(
        'Lealtad salvaje',
        800,
        'W',
        'Captura cualquier guarida neutral del mapa, que produce recursos y unidades. Héroes un 10 % más baratos y rápidos; constructores un 20 % más baratos.',
        null,
        { heroCostPct: -10, builderCostPct: -20 },
      ),
      up(
        'Murciélagos de las cavernas',
        500,
        'E',
        'Más visión y detección de unidades ocultas.',
      ),
      up(
        'Pinchos crueles',
        600,
        'R',
        'Daña a los enemigos pegados a la fortaleza.',
      ),
      up(
        'Infestación',
        1250,
        'T',
        'Arqueros de Moria con flechas de fuego en la fortaleza y fuego en todos los puestos de vigía.',
      ),
      up(
        'Prole del Norte',
        1200,
        'S',
        'Desbloquea el Dragón frío; gigantes de 2 a 5 y dragones de fuego de 2 a 4; la fortaleza puede invocar un dragón temporal.',
        null,
        { giantsMax: 5, wyrmsMax: 4 },
      ),
      up(
        'Agujas de Gundabad',
        1500,
        'D',
        '+65 % de armadura para la fortaleza y segundo batallón de la Guardia de Bolg.',
        null,
        { fortressArmourPct: 65 },
      ),
      up(
        'Tambores en las profundidades',
        500,
        'F',
        'Requiere Agujas de Gundabad. Invoca temporalmente 5 hordas de Chillones de Moria de nivel 2 y debilita a los enemigos de la zona.',
      ),
      up(
        'Expansión: Puesto de vigía',
        400,
        'W',
        'Torre de flechas; con Infestación, de fuego.',
      ),
      up(
        'Expansión: Guarida de lobos',
        500,
        'E',
        'Lobos que salen a atacar a los enemigos cercanos.',
      ),
      up(
        'Expansión: Trol centinela',
        600,
        'R',
        'Un trol que tira rocas a los enemigos.',
      ),
      up(
        'Expansión: Entrada de túnel',
        200,
        'T',
        'Conecta la fortaleza a la red de túneles.',
      ),
    ],
    abilities: [
      ab(
        'Lealtad salvaje',
        null,
        'T',
        'active',
        'Sobre una guarida neutral: mata a sus guardianes y pasa a ser tuya.',
      ),
      ab(
        'Dragón menor',
        null,
        'D',
        'active',
        'Con Prole del Norte: invoca un Dragón de fuego temporal.',
      ),
      ab(
        'Tambores en las profundidades',
        null,
        'S',
        'active',
        '5 hordas de Chillones de nivel 2 temporales; los enemigos de la zona pierden un 25 % de daño y un 20 % de armadura.',
        { hordes: 5, enemyDamagePct: -25, enemyArmourPct: -20 },
      ),
    ],
    stats: { resourcesPerCycle: 25 },
    images: { ingame: 'MM Fortress.png' },
  },
  {
    slug: 'orc-tunnel',
    name: 'Túnel orco',
    kind: 'economy',
    cost: 300,
    buildTime: 15,
    health: 2000,
    healthByLevel: [2000, 2500, 3500],
    armourSet: 'ResourceArmor',
    description:
      'El recurso principal, según el terreno libre. +50 puntos de mando, y a nivel 2 arqueros en el andamio. Cada túnel es una boca de la red: hasta cinco unidades o héroes entran por uno y salen por otro.',
    stats: { resourcesL1: 25, cp: 50, tunnelCapacity: 5 },
    images: { ingame: 'Orc Tunnel.png' },
  },
  {
    slug: 'lumber-mill',
    name: 'Aserradero',
    kind: 'economy',
    cost: 350,
    buildTime: 25,
    health: 1500,
    healthByLevel: [1500, 2000, 3000],
    armourSet: 'ResourceArmor',
    description:
      'Recurso terciario: cinco peones orcos que talan árboles cercanos (8, 10 y 12 recursos por viaje según nivel) y más peones por 20. Rinde igual esté donde esté, mientras haya bosque. +25 puntos de mando por nivel.',
    bonus:
      'Madera: las estructuras cuestan un 5 % menos por aserradero a partir del segundo, hasta un 15 %.',
    upgrades: [
      up('Peón orco', 20, null, 'Un peón más para talar (4 puntos de mando).'),
    ],
    stats: {
      labourers: 5,
      woodPerTripL1: 8,
      woodPerTripL2: 10,
      woodPerTripL3: 12,
      structureDiscountMaxPct: 15,
    },
    images: { ingame: 'LumberMill2.0 LVL1.png' },
  },
  {
    slug: 'goblin-hoard',
    name: 'Tesoro goblin',
    kind: 'economy',
    cost: 400,
    buildTime: 15,
    health: 2000,
    healthByLevel: [2000, 3500, 5000],
    armourSet: 'TechnologyArmor',
    description:
      'Recurso secundario y tienda de mejoras: estandartes y flechas de fuego a nivel 1, hojas y armadura carroñeras a nivel 2. Sube gastando en mejoras. A nivel 3 arqueros en el andamio.',
    bonus:
      'Excedente: las mejoras cuestan un 5 % menos por tesoro a partir del segundo, hasta un 20 %.',
    upgrades: [
      up(
        'Estandartes de Bolg',
        null,
        'W',
        'Permite comprar portaestandartes.',
        1,
      ),
      up('Flechas de fuego', null, 'E', 'Permite comprar Flechas de fuego.', 1),
      up(
        'Hojas carroñeras',
        null,
        'R',
        'Permite comprar Hojas carroñeras. Requiere nivel 2.',
        2,
      ),
      up(
        'Armadura carroñera',
        null,
        'T',
        'Permite comprar Armadura carroñera. Requiere nivel 2.',
        2,
      ),
    ],
    stats: { resourcesL1: 25, cp: 25, upgradeDiscountMaxPct: 20 },
    images: { ingame: 'Goblin Hoard.png' },
  },
  {
    slug: 'moria-orc-cave',
    name: 'Cueva de orcos de Moria',
    kind: 'production',
    cost: 325,
    buildTime: 15,
    health: 1500,
    healthByLevel: [1500, 3000, 4500],
    armourSet: 'FactoryArmor',
    description:
      'La fábrica del spam: barata, se levanta en 15 s y saca Chillones y Arqueros de Moria sin parar. Tres cuevas como mínimo si el plan es la marea.',
    produces: ['Chillones de Moria', 'Arqueros de Moria'],
    upgrades: [
      up(
        'Subir a nivel 2',
        350,
        'A',
        'Recluta un 10 % más rápido y guarnece dos Arqueros de Moria.',
        2,
        { recruitSpeedPct: 10 },
      ),
      up('Subir a nivel 3', 300, 'A', 'Recluta un 25 % más rápido.', 3, {
        recruitSpeedPct: 25,
      }),
    ],
    images: { ingame: 'Orc Cave Lvl 1.png' },
  },
  {
    slug: 'mountain-orc-lodge',
    name: 'Refugio de orcos de las Montañas',
    kind: 'production',
    cost: 375,
    buildTime: 25,
    health: 3000,
    healthByLevel: [3000, 4500, 6000],
    armourSet: 'FactoryArmor',
    description:
      'La infantería seria: Tajadores y Brutos a nivel 1, Exploradores a nivel 2, Berserkers y la Guardia de Bolg a nivel 3. Imprescindible en cualquier plan por ser la única fuente de picas.',
    produces: [
      'Tajadores de las Montañas',
      'Brutos de las Montañas',
      'Exploradores de las Montañas',
      'Berserkers de Gundabad',
      'Guardia de Bolg',
    ],
    upgrades: [
      up(
        'Subir a nivel 2',
        400,
        'A',
        'Exploradores de las Montañas, que además guarnecen el andamio. Recluta un 10 % más rápido.',
        2,
        { recruitSpeedPct: 10 },
      ),
      up(
        'Subir a nivel 3',
        800,
        'A',
        'Berserkers de Gundabad y Guardia de Bolg. Recluta un 25 % más rápido.',
        3,
        { recruitSpeedPct: 25 },
      ),
    ],
    images: { ingame: 'Orc Lodge Lvl 1.png' },
  },
  {
    slug: 'wolf-cairn',
    name: 'Túmulo de lobos',
    kind: 'production',
    cost: 500,
    buildTime: 30,
    health: 3000,
    healthByLevel: [3000, 4500, 6000],
    armourSet: 'FactoryArmor',
    description:
      'La caballería: Manadas de wargos a nivel 1 y Jinetes de lobo a nivel 2. Más caro que el resto, para cuando la economía ya rueda.',
    produces: ['Manada de wargos', 'Jinetes de lobo de Gundabad'],
    upgrades: [
      up(
        'Subir a nivel 2',
        500,
        'A',
        'Jinetes de lobo de Gundabad. Recluta un 10 % más rápido.',
        2,
        { recruitSpeedPct: 10 },
      ),
      up('Subir a nivel 3', 350, 'A', 'Recluta un 25 % más rápido.', 3, {
        recruitSpeedPct: 25,
      }),
    ],
    images: { ingame: 'Warg Cage.png' },
  },
  {
    slug: 'troll-lair',
    name: 'Guarida de troles',
    kind: 'production',
    cost: 500,
    buildTime: 30,
    health: 3000,
    healthByLevel: [3000, 4500, 6000],
    armourSet: 'FactoryArmor',
    description:
      'Los monstruos: Trol de las cavernas a nivel 1; Troles de las nieves y Murciélagos a nivel 2; Trol de piedra y Gigantes a nivel 3, que además pone un trol a defender la guarida. Aquí está el asedio de la facción.',
    produces: [
      'Trol de las cavernas',
      'Troles de las nieves',
      'Murciélago gigante',
      'Trol de piedra de Gundabad',
      'Gigante de las Montañas',
    ],
    upgrades: [
      up(
        'Subir a nivel 2',
        700,
        'A',
        'Troles de las nieves y Murciélagos gigantes. Recluta un 10 % más rápido.',
        2,
        { recruitSpeedPct: 10 },
      ),
      up(
        'Subir a nivel 3',
        900,
        'A',
        'Trol de piedra y Gigantes. Recluta un 25 % más rápido y un trol defiende la guarida.',
        3,
        { recruitSpeedPct: 25 },
      ),
    ],
    images: { ingame: 'Troll Lair lvl 1.png' },
  },
  {
    slug: 'wyrm-lair',
    name: 'Guarida de wyrms',
    kind: 'production',
    cost: 600,
    buildTime: 35,
    health: 3000,
    healthByLevel: [3000, 4500, 6000],
    armourSet: 'FactoryArmor',
    description:
      'Doma dragones: Dragón de fuego a nivel 1 y Dragón frío a nivel 2, ambos detrás de Prole del Norte en la fortaleza. Edificio de partida larga; a nivel 3 cura a los dragones cercanos.',
    produces: ['Dragón de fuego', 'Dragón frío'],
    upgrades: [
      up(
        'Subir a nivel 2',
        350,
        'A',
        'Dragón frío. Recluta un 10 % más rápido.',
        2,
        { recruitSpeedPct: 10 },
      ),
      up(
        'Subir a nivel 3',
        300,
        'A',
        'Cura a los dragones cercanos y recluta un 25 % más rápido.',
        3,
        { recruitSpeedPct: 25 },
      ),
    ],
    images: { ingame: 'Wyrm Lair lvl 1.png' },
  },
  {
    slug: 'sentry-tower',
    name: 'Torre de vigilancia',
    kind: 'defence',
    cost: 400,
    buildTime: 45,
    health: 1500,
    armourSet: 'FortressExpansionArmor',
    description:
      'Torre que dispara a lo que se acerque y admite guarnición. Con flechas de fuego, más daño.',
    upgrades: [up('Flechas de fuego', 200, 'W', 'Flechas incendiarias.')],
    images: { ingame: 'MM Tower.png' },
  },
  {
    slug: 'ruin-of-angmar',
    name: 'Ruina de Angmar',
    kind: 'summoned',
    health: 2000,
    maxCount: 2,
    armourSet: 'DolGuldurCitadelArmor',
    description:
      'Se invoca con el poder de 10 PP (máximo dos). Recluta Muertos de Arnor y Lobos blancos, y su Frío de Angmar frena y quita el liderazgo a los enemigos cercanos.',
    produces: ['Muertos de Arnor', 'Lobos blancos'],
    abilities: [
      ab(
        'Frío de Angmar',
        null,
        null,
        'passive',
        'Los enemigos cercanos van más lentos y pierden todo liderazgo.',
      ),
    ],
    images: { ingame: 'Ruin of Angmar.png' },
  },
];

const powers: PowerData[] = [
  {
    slug: 'fell-wind',
    name: 'Viento maligno',
    tier: 1,
    position: 'L',
    kind: 'attack',
    description:
      'Dispersa a las tropas enemigas desde el centro de la zona. Daño mínimo; no afecta a la caballería.',
  },
  {
    slug: 'frozen-wastes',
    name: 'Yermos helados',
    tier: 1,
    position: 'C',
    kind: 'buff',
    description:
      'Congela una zona 90 s: aliados con +25 % de daño y armadura, enemigos con -10 % de velocidad. Apaga todos los fuegos.',
    stats: { durationS: 90, damagePct: 25, armourPct: 25, enemySpeedPct: -10 },
  },
  {
    slug: 'cave-bats',
    name: 'Murciélagos de las cavernas',
    tier: 1,
    position: 'R',
    kind: 'debuff',
    description:
      'Revela la zona y detecta unidades ocultas. Los enemigos de dentro pierden un 15 % de daño y de armadura.',
    stats: { enemyDamagePct: -15, enemyArmourPct: -15 },
  },
  {
    slug: 'scavenger',
    name: 'Carroñero',
    tier: 2,
    position: 'LL',
    kind: 'utility',
    description:
      'Durante 180 s cada muerte da recursos extra y las mejoras de unidad cuestan un 25 % menos.',
    stats: { durationS: 180, upgradeDiscountPct: 25 },
  },
  {
    slug: 'they-are-coming',
    name: '¡Ya vienen!',
    tier: 2,
    position: 'LR',
    kind: 'summon',
    description:
      'De un Túnel orco (o del túnel del Gusano) salen dos hordas permanentes de Chillones de Moria y un Trol destructor. Los orcos cuentan para el límite de mando; el trol no. En la 9.2.0 bajó de cuatro hordas a dos.',
    stats: { hordes: 2, trolls: 1 },
  },
  {
    slug: 'ruin-of-angmar',
    name: 'Ruina de Angmar',
    tier: 2,
    position: 'RL',
    kind: 'summon',
    description:
      'Levanta una Ruina de Angmar (máximo dos) que recluta Muertos de Arnor y Lobos blancos y desata una tormenta de nieve local.',
    stats: { maxCount: 2 },
  },
  {
    slug: 'trollish-stew',
    name: 'Guiso de trol',
    tier: 2,
    position: 'RR',
    kind: 'heal',
    description:
      'Un caldero temporal custodiado por Tom, Berto y Guille: cura, da +15 % de armadura y daño a las tropas cercanas y detecta sigilo.',
    stats: { armourPct: 15, damagePct: 15 },
  },
  {
    slug: 'summon-were-worm',
    name: 'Invocar Gusano',
    tier: 3,
    position: 'L',
    kind: 'summon',
    description:
      'Un Gusano subterráneo bajo tu control durante 60 s, con un túnel enlazado a tu red. Desde la 9.2.0 no pierde el objetivo que se le ordena, a cambio de menos resistencia y daño.',
    stats: { durationS: 60 },
  },
  {
    slug: 'white-winter',
    name: 'Invierno blanco',
    tier: 3,
    position: 'C',
    kind: 'debuff',
    description:
      'Una ventisca cubre el mapa un rato: los enemigos pierden un 25 % de daño, un 20 % de armadura y un 30 % de visión y todo su liderazgo. Disipa los climas rivales. No se acumula con otras penalizaciones.',
    stats: { enemyDamagePct: -25, enemyArmourPct: -20, enemyVisionPct: -30 },
  },
  {
    slug: 'summon-watcher',
    name: 'Invocar al Vigilante',
    tier: 3,
    position: 'R',
    kind: 'summon',
    description:
      'El Vigilante del Agua emerge 30 s donde se señale, derribando a todo lo que hay encima y azotando alrededor.',
    stats: { durationS: 30 },
  },
  {
    slug: 'durins-bane',
    name: 'Daño de Durin',
    tier: 4,
    position: 'L',
    kind: 'summon',
    description: 'Invoca al Balrog durante 100 s.',
    stats: { durationS: 100 },
  },
  {
    slug: 'fire-drakes-wrath',
    name: 'Ira de los dragones de fuego',
    tier: 4,
    position: 'R',
    kind: 'attack',
    description: 'Un dragón sobrevuela la zona y la abrasa a su paso.',
  },
];

const misty: FactionData = {
  code: 'mistyMountains',
  heroes,
  units,
  structures,
  powers,
};

export { misty };
